// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildFlagComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx } from "@emotion/core";
import PropTypes from "prop-types";
import flagStyles from "../Flag.styles";

function FlagBolivia(props) {
  return (
    <svg
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 86 64"
      className="gds-flag"
      css={flagStyles}
      {...props}
    >
      <path d="M84.299 0H0v64h84.299V0z" fill="#008C4B" />
      <path d="M84.299 0H0v22.613h84.299V0z" fill="#E43B3A" />
      <path d="M84.299 21.349H0V42.65h84.299V21.35z" fill="#F1B920" />
      <path
        d="M42.222 36.9c2.506 0 4.538-1.76 4.538-3.928 0-2.17-2.032-3.928-4.538-3.928-2.506 0-4.538 1.759-4.538 3.928s2.032 3.927 4.538 3.927z"
        stroke="#0C9AD0"
        strokeWidth={1.992}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M43.095 28.813s.174-1.92 1.105-2.735a6.359 6.359 0 0 0 2.21 1.63l-1.599 1.948M45.946 30.5l4.625-2.822s-1.81 2.494-1.455 4.916c.32 2.182-.233 3.898-3.578 3.723"
        stroke="#0C9AD0"
        strokeWidth={1.992}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="m49.349 31.14 3.374-2.192s-1.635 2.359-1.28 4.78c.32 2.182-.407 4.034-3.752 3.86 0 0-1.804.068-2.502-1.445M41.204 28.813s-.175-1.92-1.105-2.735a6.358 6.358 0 0 1-2.211 1.63l1.6 1.948M38.353 30.5l-4.625-2.822s1.81 2.494 1.455 4.916c-.32 2.182.232 3.898 3.577 3.723"
        stroke="#0C9AD0"
        strokeWidth={1.992}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="m34.95 31.14-3.374-2.192s1.635 2.359 1.28 4.78c-.32 2.182.407 4.034 3.752 3.86 0 0 1.803.068 2.502-1.445"
        stroke="#0C9AD0"
        strokeWidth={1.992}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}
export default FlagBolivia;

FlagBolivia.propTypes = {
  width: PropTypes.string,
  height: PropTypes.string,
};

FlagBolivia.defaultProps = {};
