// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildFlagComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx } from "@emotion/core";
import PropTypes from "prop-types";
import flagStyles from "../Flag.styles";

function FlagTanzania(props) {
  return (
    <svg
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 86 64"
      className="gds-flag"
      css={flagStyles}
      {...props}
    >
      <path d="M84.294 0H0v64h84.294V0z" fill="#F1B924" />
      <path
        d="M69.174 0C51.156 13.723 11.546 43.925 0 52.674V0h69.174z"
        fill="#008C4C"
      />
      <path
        d="M84.294 10.727V64H14.342C31.24 51.136 71.55 20.395 84.294 10.727z"
        fill="#0099CE"
      />
      <path
        d="M84.294 0v5.134L7.511 64H0v-6.272L75.306 0h8.988z"
        fill="#231F20"
      />
    </svg>
  );
}
export default FlagTanzania;

FlagTanzania.propTypes = {
  width: PropTypes.string,
  height: PropTypes.string,
};

FlagTanzania.defaultProps = {};
