// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildFlagComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

import PropTypes from "prop-types";
import flagStyles from "../Flag.styles";

function FlagTogo(props) {
  return (
    <svg
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 86 64"
      className="gds-flag"
      css={flagStyles}
      {...props}
    >
      <path d="M84.299 0H.004v64h84.295V0Z" fill="#008C4C" />
      <path
        d="M84.298 12.804H.003v12.8h84.295v-12.8ZM84.295 38.404H0v12.799h84.295v-12.8Z"
        fill="#F1B924"
      />
      <path d="M38.606 0H.004v38.394h38.602V0Z" fill="#E43B3A" />
      <path
        d="m7.67 16.427 8.033-1.109 3.878-7.48 3.463 7.48 7.895 1.109-5.68 5.956 1.248 8.172-7.203-4.017-7.203 4.017 1.524-8.45-5.956-5.678Z"
        fill="#fff"
      />
    </svg>
  );
}
export default FlagTogo;

FlagTogo.propTypes = {
  width: PropTypes.string,
  height: PropTypes.string,
};

FlagTogo.defaultProps = {};
