// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildFlagComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx } from "@emotion/core";
import PropTypes from "prop-types";
import flagStyles from "../Flag.styles";

function FlagThailand(props) {
  return (
    <svg
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 86 64"
      className="gds-flag"
      css={flagStyles}
      {...props}
    >
      <path d="M84.299 0H0v64h84.299V0z" fill="#E43B3A" />
      <path d="M84.299 10.602H0v42.796h84.299V10.602z" fill="#E7E7E8" />
      <path d="M84.299 21.241H0V42.76h84.299V21.24z" fill="#0099CE" />
    </svg>
  );
}
export default FlagThailand;

FlagThailand.propTypes = {
  width: PropTypes.string,
  height: PropTypes.string,
};

FlagThailand.defaultProps = {};
