// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildFlagComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx } from "@emotion/core";
import PropTypes from "prop-types";
import flagStyles from "../Flag.styles";

function FlagBrazil(props) {
  return (
    <svg
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 86 64"
      className="gds-flag"
      css={flagStyles}
      {...props}
    >
      <path d="M84.299 0H0v64h84.299V0z" fill="#008C4B" />
      <path
        d="m8.672 31.118 33.57-21.33 33.385 21.33-33.2 22.998L8.672 31.118z"
        fill="#F1B920"
      />
      <path
        d="M56.857 31.946c0 .394-.02.787-.06 1.179a14.124 14.124 0 0 1-.639 3.315 14.711 14.711 0 0 1-28.723-4.494 14.25 14.25 0 0 1 .98-5.233c.338-.952.795-1.858 1.357-2.697a14.705 14.705 0 0 1 27.085 7.93z"
        fill="#0C9AD0"
      />
      <path
        d="M56.798 33.125a14.122 14.122 0 0 1-.64 3.315l-.06.04c-6.81-9.148-24.348-9.747-27.684-9.767.34-.952.795-1.858 1.358-2.697 5.254.16 19.495 1.319 27.026 9.109z"
        fill="#EBEDED"
      />
    </svg>
  );
}
export default FlagBrazil;

FlagBrazil.propTypes = {
  width: PropTypes.string,
  height: PropTypes.string,
};

FlagBrazil.defaultProps = {};
