// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildFlagComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

import PropTypes from "prop-types";
import flagStyles from "../Flag.styles";

function FlagColumbia(props) {
  return (
    <svg
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 86 64"
      className="gds-flag"
      css={flagStyles}
      {...props}
    >
      <path d="M84.299 0H0v64h84.299V0Z" fill="#E43B3A" />
      <path d="M84.299 0H0v32.612h84.299V0Z" fill="#F1B920" />
      <path d="M84.299 31.35H0v16.098h84.299V31.35Z" fill="#0C9AD0" />
    </svg>
  );
}
export default FlagColumbia;

FlagColumbia.propTypes = {
  width: PropTypes.string,
  height: PropTypes.string,
};

FlagColumbia.defaultProps = {};
