// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildFlagComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx } from "@emotion/core";
import PropTypes from "prop-types";
import flagStyles from "../Flag.styles";

function FlagRwanda(props) {
  return (
    <svg
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 86 64"
      className="gds-flag"
      css={flagStyles}
      {...props}
    >
      <path d="M84.295 44.748H0V64h84.295V44.748z" fill="#008C4C" />
      <path d="M84.295 0H0v32.355h84.295V0z" fill="#0099CE" />
      <path
        d="M84.295 32.355H0v16.058h84.295V32.355zM74.569 16.06l5.093-.76-5.053-.658 4.614-2.038-4.914.64 4.195-3.256-4.894 2.037 2.916-4.115-4.075 3.156 1.998-4.834-3.196 4.075.759-5.173-2.097 4.914-.66-5.353s-.699 5.093-.739 5.253L66.44 4.834l.659 5.394-3.076-3.975 1.937 4.714-4.274-3.136 3.196 4.154-4.874-2.057 4.215 3.316-5.174-.68 4.794 2.038-5.173.68 5.133.758-4.754 1.998 5.174-.64-4.255 3.297 4.914-2.038-3.256 4.335 4.275-3.416-1.818 4.714 3.016-3.835-.62 5.074 1.978-4.814.8 5.233.659-5.233 2.097 4.893-.76-5.293 3.157 3.955-1.878-4.654 4.175 3.116-3.116-4.015 4.914 1.918-4.255-3.136 4.834.38-4.514-1.819zm-5.414 4.155a4.754 4.754 0 1 1 0-9.508 4.754 4.754 0 0 1 0 9.508z"
        fill="#F1B924"
      />
      <path
        d="M73.13 15.46a3.964 3.964 0 1 1-7.928.021 3.964 3.964 0 0 1 7.928-.02z"
        fill="#F1B924"
      />
    </svg>
  );
}
export default FlagRwanda;

FlagRwanda.propTypes = {
  width: PropTypes.string,
  height: PropTypes.string,
};

FlagRwanda.defaultProps = {};
