// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildFlagComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

import PropTypes from "prop-types";
import flagStyles from "../Flag.styles";

function FlagBurkinaFaso(props) {
  return (
    <svg
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 86 64"
      className="gds-flag"
      css={flagStyles}
      {...props}
    >
      <path d="M84.299 0H0v64h84.299V0Z" fill="#008C4B" />
      <path d="M84.299 0H0v32.612h84.299V0Z" fill="#E43B3A" />
      <path
        d="m42.24 22.47 3.433 6.685 7.045 1.084-4.878 5.24 1.265 7.406-6.865-3.432-6.684 3.613 1.625-7.407-5.6-5.6 7.588-.904 3.071-6.684Z"
        fill="#F1B920"
      />
    </svg>
  );
}
export default FlagBurkinaFaso;

FlagBurkinaFaso.propTypes = {
  width: PropTypes.string,
  height: PropTypes.string,
};

FlagBurkinaFaso.defaultProps = {};
