// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildFlagComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

import PropTypes from "prop-types";
import flagStyles from "../Flag.styles";

function FlagBangladesh(props) {
  return (
    <svg
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 86 64"
      className="gds-flag"
      css={flagStyles}
      {...props}
    >
      <path d="M84.299 0H0v64h84.299V0Z" fill="#008C4B" />
      <path
        d="M42.15 47.734c8.689 0 15.733-7.044 15.733-15.734 0-8.69-7.044-15.733-15.733-15.733-8.69 0-15.734 7.044-15.734 15.733 0 8.69 7.044 15.734 15.734 15.734Z"
        fill="#E43B3A"
      />
    </svg>
  );
}
export default FlagBangladesh;

FlagBangladesh.propTypes = {
  width: PropTypes.string,
  height: PropTypes.string,
};

FlagBangladesh.defaultProps = {};
