// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildFlagComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

import PropTypes from "prop-types";
import flagStyles from "../Flag.styles";

function FlagElSalvador(props) {
  return (
    <svg
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 86 64"
      className="gds-flag"
      css={flagStyles}
      {...props}
    >
      <path d="M84.299 0H0v64h84.299V0Z" fill="#0C9AD0" />
      <path d="M84.299 21.637H0v21.36h84.299v-21.36Z" fill="#EBEDED" />
      <path
        d="M42.15 39.847a7.42 7.42 0 1 0 0-14.842 7.42 7.42 0 0 0 0 14.842Z"
        stroke="#F1B920"
        strokeWidth={0.697}
        strokeMiterlimit={10}
      />
      <path
        d="M42.15 27.852 38.2 34.594h7.897l-3.948-6.742ZM46.796 30.433l-1.245.01.644 1.08.6-1.09Z"
        fill="#0C9AD0"
      />
      <path
        d="m43.862 32.285-.191-.35 2.409-1.306.191.35-2.41 1.306ZM37.503 30.433l1.245.01-.643 1.08-.602-1.09Z"
        fill="#0C9AD0"
      />
      <path
        d="m40.436 32.286-2.408-1.306.191-.351 2.409 1.306-.192.35ZM45.552 27.87l-1.148.483 1.007.755.141-1.238Z"
        fill="#0C9AD0"
      />
      <path
        d="m43.544 30.7-.308-.25 1.73-2.126.308.252-1.73 2.125ZM38.747 27.87l1.148.483-1.008.755-.14-1.238Z"
        fill="#0C9AD0"
      />
      <path
        d="m40.755 30.7-1.73-2.124.308-.252 1.73 2.125-.308.252ZM42.15 25.998l-.63 1.075h1.26l-.63-1.075Z"
        fill="#0C9AD0"
      />
      <path d="M42.333 26.906h-.398v2.947h.398v-2.947Z" fill="#0C9AD0" />
      <path
        d="M47.952 32.852a5.808 5.808 0 0 1-11.605 0 5.42 5.42 0 0 1 1.698-3.935 5.125 5.125 0 1 0 8.21 0 5.497 5.497 0 0 1 1.697 3.935Z"
        fill="#0C9AD0"
      />
    </svg>
  );
}
export default FlagElSalvador;

FlagElSalvador.propTypes = {
  width: PropTypes.string,
  height: PropTypes.string,
};

FlagElSalvador.defaultProps = {};
