// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildFlagComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

import PropTypes from "prop-types";
import flagStyles from "../Flag.styles";

function FlagGhana(props) {
  return (
    <svg
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 86 64"
      className="gds-flag"
      css={flagStyles}
      {...props}
    >
      <path d="M84.315 42.367H0V64h84.315V42.367Z" fill="#008C4B" />
      <path d="M84.315 0H0v21.014h84.315V0Z" fill="#E43B3A" />
      <path d="M84.315 21.014H0v21.353h84.315V21.014Z" fill="#F1B920" />
      <path
        d="m42.252 20.893 3.606 7.021 7.4 1.139-5.123 5.503 1.328 7.78-7.211-3.605-7.021 3.795 1.708-7.78-5.883-5.883 7.97-.949 3.226-7.02Z"
        fill="#000"
      />
    </svg>
  );
}
export default FlagGhana;

FlagGhana.propTypes = {
  width: PropTypes.string,
  height: PropTypes.string,
};

FlagGhana.defaultProps = {};
