function template(variables, { tpl }) {
  return tpl`
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildIconComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

import React from 'react';
import PropTypes from 'prop-types';
import iconStyles from '../Icon.styles';

${variables.interfaces};
const ${variables.componentName} = (${variables.props}) => (
  ${variables.jsx}
);

${variables.componentName}.propTypes = {
  /**
   * A CSS fill color.
   */
  fill: PropTypes.string,
  /**
   * Any valid CSS width value.
   */
  width: PropTypes.string,
  /**
   * Any valid CSS height value.
   */
  height: PropTypes.string,
};

${variables.componentName}.defaultProps = {
  fill: 'currentColor',
  width: '100%',
  height: '100%',
};
 
${variables.exports};
`;
}

module.exports = template;
