import * as a from './src/a11y';
import b from './src/breakpoints';
import c from './src/color';
import d from './src/depth';
import * as f from './src/flags';
import * as h from './src/helpers';
import * as i from './src/icons';
import * as m from './src/motion';
import s from './src/size';
import sp from './src/space';
import * as t from './src/typography';

export const a11y = a;
export const breakpoints = b;
export const color = c;
export const depth = d;
export const flags = f;
export const helpers = h;
export const icons = i;
export const motion = m;
export const size = s;
export const space = sp;
export const typography = t;
