// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildFlagComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx } from "@emotion/core";
import PropTypes from "prop-types";
import flagStyles from "../Flag.styles";

function FlagSwitzerland(props) {
  return (
    <svg
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 86 64"
      className="gds-flag"
      css={flagStyles}
      {...props}
    >
      <path d="M84.315 0H0v64h84.315V0z" fill="#E43B3A" />
      <path d="M48.906 13.732H35.408v36.536h13.498V13.732z" fill="#EBEDED" />
      <path d="M60.426 38.749V25.25H23.889V38.75h36.537z" fill="#EBEDED" />
    </svg>
  );
}
export default FlagSwitzerland;

FlagSwitzerland.propTypes = {
  width: PropTypes.string,
  height: PropTypes.string,
};

FlagSwitzerland.defaultProps = {};
