// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildFlagComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx } from "@emotion/core";
import PropTypes from "prop-types";
import flagStyles from "../Flag.styles";

function FlagUK(props) {
  return (
    <svg
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 86 64"
      className="gds-flag"
      css={flagStyles}
      {...props}
    >
      <path d="M84.314 0H0v64h84.314V0z" fill="#EBEDED" />
      <path
        d="M84.314 28.624v6.112h-39.09V64H39.13V34.736H0v-6.112h39.131V0h6.092v28.624h39.091z"
        fill="#E43B3A"
      />
      <path
        d="m4.455 0 31.74 25.408v.9h-3.676L0 .578V0h4.455zM84.314 63.94V64H80.16L47.9 38.472v-.46h4.055l32.36 25.928zM32.66 38.012h3.535v.88L4.455 64H.22l32.44-25.988zM84.314 0v.799l-32.24 25.508H47.9v-.48L80.16 0h4.154z"
        fill="#E43B3A"
      />
      <path
        d="M29.843 26.307H0V2.677l29.843 23.63zM36.295 0v23.65L6.352 0h29.943zM84.314 2.557v23.75H54.332l29.982-23.75zM77.822 0 47.9 23.65V0h29.922zM29.843 38.052 0 61.702v-23.65h29.843zM36.294 40.71V64H6.831l29.463-23.29zM84.314 38.052v23.75l-29.982-23.75h29.982zM77.363 64H47.9V40.71L77.363 64z"
        fill="#0C9AD0"
      />
    </svg>
  );
}
export default FlagUK;

FlagUK.propTypes = {
  width: PropTypes.string,
  height: PropTypes.string,
};

FlagUK.defaultProps = {};
