// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildFlagComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

import PropTypes from "prop-types";
import flagStyles from "../Flag.styles";

function FlagNetherlands(props) {
  return (
    <svg
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 86 64"
      className="gds-flag"
      css={flagStyles}
      {...props}
    >
      <path d="M84.295 0H0v21.094h84.295V0Z" fill="#E43B3A" />
      <path d="M84.295 21.094H0V64h84.295V21.094Z" fill="#0099CE" />
      <path d="M84.295 21.094H0v21.812h84.295V21.094Z" fill="#E7E7E8" />
    </svg>
  );
}
export default FlagNetherlands;

FlagNetherlands.propTypes = {
  width: PropTypes.string,
  height: PropTypes.string,
};

FlagNetherlands.defaultProps = {};
