// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildFlagComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

import PropTypes from "prop-types";
import flagStyles from "../Flag.styles";

function FlagNorway(props) {
  return (
    <svg
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 86 64"
      className="gds-flag"
      css={flagStyles}
      {...props}
    >
      <path d="M84.314 0H0v64h84.314V0Z" fill="#E43B3A" />
      <path d="M84.314 25.748H0v12.524h84.314V25.748Z" fill="#EBEDED" />
      <path d="M38.272 0H25.748v64h12.524V0Z" fill="#EBEDED" />
      <path d="M34.916 0h-5.812v64h5.812V0Z" fill="#0C9AD0" />
      <path d="M84.314 29.004H0v6.012h84.314v-6.012Z" fill="#0C9AD0" />
    </svg>
  );
}
export default FlagNorway;

FlagNorway.propTypes = {
  width: PropTypes.string,
  height: PropTypes.string,
};

FlagNorway.defaultProps = {};
