// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildFlagComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx } from "@emotion/core";
import PropTypes from "prop-types";
import flagStyles from "../Flag.styles";

function FlagIreland(props) {
  return (
    <svg
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 86 64"
      className="gds-flag"
      css={flagStyles}
      {...props}
    >
      <path d="M84.314 0H56.11v64h28.204V0z" fill="#F1B920" />
      <path d="M28.185 0H0v64h28.185V0z" fill="#008C4B" />
      <path d="M56.11 0H28.185v64H56.11V0z" fill="#EBEDED" />
    </svg>
  );
}
export default FlagIreland;

FlagIreland.propTypes = {
  width: PropTypes.string,
  height: PropTypes.string,
};

FlagIreland.defaultProps = {};
