// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildFlagComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx } from "@emotion/core";
import PropTypes from "prop-types";
import flagStyles from "../Flag.styles";

function FlagFrance(props) {
  return (
    <svg
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 86 64"
      className="gds-flag"
      css={flagStyles}
      {...props}
    >
      <path d="M85.333 0H56.788v64h28.545V0z" fill="#E43B3A" />
      <path d="M28.525 0H0v64h28.525V0z" fill="#0099CE" />
      <path d="M56.788 0H28.525v64h28.263V0z" fill="#EBEDED" />
    </svg>
  );
}
export default FlagFrance;

FlagFrance.propTypes = {
  width: PropTypes.string,
  height: PropTypes.string,
};

FlagFrance.defaultProps = {};
