// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildFlagComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx } from "@emotion/core";
import PropTypes from "prop-types";
import flagStyles from "../Flag.styles";

function FlagDenmark(props) {
  return (
    <svg
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 86 64"
      className="gds-flag"
      css={flagStyles}
      {...props}
    >
      <path d="M85.333 0H0v64h85.333V0z" fill="#E43B3A" />
      <path d="M85.333 29.124H0v5.752h85.333v-5.752z" fill="#EBEDED" />
      <path d="M35.237 0h-5.842v64h5.842V0z" fill="#EBEDED" />
    </svg>
  );
}
export default FlagDenmark;

FlagDenmark.propTypes = {
  width: PropTypes.string,
  height: PropTypes.string,
};

FlagDenmark.defaultProps = {};
