// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildFlagComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx } from "@emotion/core";
import PropTypes from "prop-types";
import flagStyles from "../Flag.styles";

function FlagCanada(props) {
  return (
    <svg
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 86 64"
      className="gds-flag"
      css={flagStyles}
      {...props}
    >
      <path
        d="M85.333 0H56.788v64h28.545V0zM28.525 0H0v64h28.525V0z"
        fill="#E43B3A"
      />
      <path d="M56.788 0H28.525v64h28.263V0z" fill="#EBEDED" />
      <path
        d="m42.044 37.965-.087 6.958h1.304v-6.786l5.652 1.03-.435-1.975 6.086-5.155L53 31.007l1.043-3.78-3.477.6-.957-1.975-3.478 3.866 1.218-7.302-2.348.859-2.347-4.038-2.435 3.866-2.348-.688 1.044 7.131-3.304-3.436-1.043 1.546-3.478-.43.957 3.866-1.652.945 6.26 5.155-.348 1.89 5.738-1.117z"
        fill="#E43B3A"
      />
    </svg>
  );
}
export default FlagCanada;

FlagCanada.propTypes = {
  width: PropTypes.string,
  height: PropTypes.string,
};

FlagCanada.defaultProps = {};
