// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildFlagComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

import PropTypes from "prop-types";
import flagStyles from "../Flag.styles";

function FlagSweden(props) {
  return (
    <svg
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 86 64"
      className="gds-flag"
      css={flagStyles}
      {...props}
    >
      <path d="M84.315 0H0v64h84.315V0Z" fill="#0C9AD0" />
      <path d="M84.315 25.648H0v12.684h84.315V25.648Z" fill="#F1B920" />
      <path d="M38.272 0H25.588v64h12.684V0Z" fill="#F1B920" />
    </svg>
  );
}
export default FlagSweden;

FlagSweden.propTypes = {
  width: PropTypes.string,
  height: PropTypes.string,
};

FlagSweden.defaultProps = {};
