import { CdsTokens } from '../components';

export const cdsDarkTokens: CdsTokens = {
  typeHeadingH1DesktopRegular: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 52,
    fontSize: 49,
  },
  typeHeadingH1DesktopBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 52,
    fontSize: 49,
  },
  typeHeadingH1MobileRegular: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 32,
    fontSize: 31,
  },
  typeHeadingH1MobileBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 32,
    fontSize: 31,
  },
  typeHeadingH2DesktopRegular: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 40,
    fontSize: 39,
  },
  typeHeadingH2DesktopBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 40,
    fontSize: 39,
  },
  typeHeadingH2MobileRegular: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 32,
    fontSize: 31,
  },
  typeHeadingH2MobileBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 32,
    fontSize: 31,
  },
  typeHeadingH3DesktopRegular: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 32,
    fontSize: 31,
  },
  typeHeadingH3DesktopBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 32,
    fontSize: 31,
  },
  typeHeadingH3MobileRegular: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 28,
    fontSize: 25,
  },
  typeHeadingH3MobileBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 28,
    fontSize: 25,
  },
  typeHeadingH4DesktopRegular: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 28,
    fontSize: 25,
  },
  typeHeadingH4DesktopBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 28,
    fontSize: 25,
  },
  typeHeadingH4MobileRegular: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 20,
  },
  typeHeadingH4MobileBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 20,
  },
  typeHeadingH5DesktopRegular: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 20,
  },
  typeHeadingH5DesktopBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 20,
  },
  typeHeadingH5MobileRegular: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  typeHeadingH5MobileBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  typeHeadingH6DesktopRegular: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  typeHeadingH6DesktopBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  typeHeadingH6MobileRegular: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  typeHeadingH6MobileBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  typeHeadingRegular: { fontFamily: 'Gotham-Book', fontWeight: 'normal' },
  typeHeadingSemibold: { fontFamily: 'Gotham-Medium', fontWeight: 'normal' },
  typeHeadingBold: { fontFamily: 'Gotham-Bold', fontWeight: 'normal' },
  typeBodyPDesktopRegular: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  typeBodyPDesktopBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  typeBodyPMobileRegular: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  typeBodyPMobileBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  typeBodyPSmallDesktopRegular: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 16,
    fontSize: 13,
  },
  typeBodyPSmallDesktopBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 16,
    fontSize: 13,
  },
  typeBodyPSmallMobileRegular: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 16,
    fontSize: 13,
  },
  typeBodyPSmallMobileBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 16,
    fontSize: 13,
  },
  typeBodyRegular: { fontFamily: 'Gotham-Book', fontWeight: 'normal' },
  typeBodySemibold: { fontFamily: 'Gotham-Medium', fontWeight: 'normal' },
  typeBodyBold: { fontFamily: 'Gotham-Bold', fontWeight: 'normal' },
  typeColor: '#FFFFFF',
  typeColorWhite: '#FFFFFF',
  typeColorAccent: '#FFD05C',
  typeColorPrimary: '#61B3FF',
  typeCaseUppercase: 'uppercase',
  typeMarginBottomDesktop: 16,
  typeMarginBottomMobile: 16,
  tooltipPaddingX: 8,
  tooltipPaddingY: 4,
  tooltipBorderRadius: 4,
  tooltipBorderWidth: 1,
  tooltipFont: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 13,
    fontSize: 10,
  },
  tooltipBackgroundColor: '#FFFFFF',
  tooltipBorderColor: '#FFFFFF',
  tooltipTextColor: '#1d1e1b',
  toastBackgroundColor: '#2e2f2a',
  toastBodyColor: '#FFFFFF',
  toastBorderColor: '#4b4c45',
  toastActionColor: '#61B3FF',
  toastBorderRadius: 8,
  toastShadow: '0 0.95 1.55 -2.5 #00000012, 0 7.5 12.5 -2.5 #00000024',
  toastButtonFont: {
    fontSize: 16,
    letterSpacing: '',
    lineHeight: 20,
    fontWeight: 'normal',
    fontFamily: 'Gotham-Bold',
  },
  tableBackgroundColor: '#2e2f2a',
  tableBorderColor: '#4b4c45',
  tableNoBackground: '#00000000',
  tableHeaderColor: '#FFFFFF',
  tableTextColor: '#FFFFFF',
  tableActionColor: '#61B3FF',
  tableHoverBackgroundColor: '#004180',
  tableActiveBackgroundColor: '#4b4c45',
  tableActiveActionColor: '#ecedec',
  tableDisabledBackgroundColor: '#2e2f2a',
  tableDisabledActionColor: '#919389',
  tableDisabledHeaderColor: '#acaea7',
  tableDisabledTextColor: '#acaea7',
  tableBorderRadius: 0,
  tableBorderWidth: 1,
  tableNoBorder: 0,
  tableHeaderFont: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  tableCellFont: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  tabBackgroundColor: '#2e2f2a',
  tabBorderColor: '#4b4c45',
  tabNoBackground: '#00000000',
  tabUnderlineColor: '#4b4c45',
  tabActionColor: '#61B3FF',
  tabHoverBackgroundColor: '#004180',
  tabActiveBackgroundColor: '#4b4c45',
  tabActiveActionColor: '#ecedec',
  tabDisabledBackgroundColor: '#2e2f2a',
  tabDisabledActionColor: '#919389',
  tabBorderRadius: 4,
  tabShadow: '0 0.475 0.6 -1.25 #00000014, 0 3.75 5 -1.25 #00000026',
  tabNoShadow: '0 0 0 0 #00000000',
  tabBorderWidth: 1,
  tabNoBorder: 0,
  tabPaddingX: 16,
  tabPaddingY: 12,
  tabFont: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  margin1: 8,
  margin2: 12,
  margin3: 16,
  margin4: 24,
  margin5: 32,
  padding1: 8,
  padding2: 12,
  padding3: 16,
  padding4: 24,
  padding5: 32,
  progressLabel: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 16,
    fontSize: 13,
  },
  progressProgressColor: '#61B3FF',
  progressBackgroundColor: '#4b4c45',
  progressLabelColor: '#FFFFFF',
  progressDefaultHeight: 8,
  progressSmallHeight: 4,
  progressLargeHeight: 12,
  paginationBackgroundColor: '#2e2f2a',
  paginationBorderColor: '#4b4c45',
  paginationActionColor: '#61B3FF',
  paginationHoverBackgroundColor: '#004180',
  paginationActiveBackgroundColor: '#4b4c45',
  paginationActiveActionColor: '#ecedec',
  paginationDisabledBackgroundColor: '#2e2f2a',
  paginationDisabledActionColor: '#919389',
  paginationBorderRadius: 8,
  paginationShadow: '0 0.475 0.6 -1.25 #00000014, 0 3.75 5 -1.25 #00000026',
  paginationMdPaddingX: 16,
  paginationMdPaddingY: 12,
  paginationMdFont: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  paginationSmFont: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 16,
    fontSize: 13,
  },
  paginationSmPaddingX: 12,
  paginationSmPaddingY: 8,
  paginationLgFont: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 20,
  },
  paginationLgPaddingX: 16,
  paginationLgPaddingY: 12,
  navBackgroundColor: '#2e2f2a',
  navBorderColor: '#4b4c45',
  navUnderlineColor: '#4b4c45',
  navActionColor: '#61B3FF',
  navHoverBackgroundColor: '#004180',
  navActiveBackgroundColor: '#4b4c45',
  navActiveActionColor: '#ecedec',
  navDisabledBackgroundColor: '#2e2f2a',
  navDisabledActionColor: '#919389',
  navBorderWidth: 1,
  navNoBorder: 0,
  navPaddingX: 16,
  navPaddingY: 12,
  navLinkFont: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  navSubnavLinkFont: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 16,
    fontSize: 13,
  },
  modalBorderRadius: 8,
  modalShadow: '0 0.95 1.55 -2.5 #00000012, 0 7.5 12.5 -2.5 #00000024',
  modalBackgroundColor: '#2e2f2a',
  modalHeaderColor: '#FFFFFF',
  modalBodyColor: '#FFFFFF',
  modalBorderColor: '#4b4c45',
  modalHeaderFont: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    fontSize: 25,
    lineHeight: 28,
  },
  modalBodyFont: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  modalDefaultMaxWidth: 660,
  modalSmallMaxWidth: 320,
  modalWideMaxWidth: 990,
  listGroupBackgroundColor: '#2e2f2a',
  listGroupBorderColor: '#4b4c45',
  listGroupUnderlineColor: '#4b4c45',
  listGroupIconColor: '#61B3FF',
  listGroupBodyColor: '#FFFFFF',
  listGroupHeadingColor: '#FFFFFF',
  listGroupHoverBackgroundColor: '#004180',
  listGroupActiveBackgroundColor: '#4b4c45',
  listGroupActiveIconColor: '#ecedec',
  listGroupActiveHeadingColor: '#ecedec',
  listGroupActiveBodyColor: '#ecedec',
  listGroupDisabledBackgroundColor: '#2e2f2a',
  listGroupDisabledHeadingColor: '#919389',
  listGroupDisabledBodyColor: '#919389',
  listGroupDisabledIconColor: '#919389',
  listGroupBorderRadius: 8,
  listGroupBorderWidth: 1,
  listGroupNoBorder: 0,
  listGroupPaddingX: 16,
  listGroupPaddingY: 12,
  listGroupHeadingFont: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  listGroupActionFont: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  listGroupBodyFont: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  listGroupImageBorderRadiusDefault: 0,
  listGroupImageBorderRadiusRounded: 8,
  listGroupImageBorderRadiusCircle: 512,
  linkColorDefault: '#61B3FF',
  linkColorWhite: '#FFFFFF',
  linkTextDecorationUnderline: 'underline',
  linkFontDefault: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  linkFontBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  imageBackgroundColor: '#4b4c45',
  imageIconColor: '#919389',
  imageIconColorInverse: '#FFFFFF',
  iconColorDefault: '#FFFFFF',
  iconColorMuted: '#ecedec',
  iconColorPrimary: '#61B3FF',
  iconColorWhite: '#FFFFFF',
  headerDefaultBackgroundColor: '#1d1e1b',
  headerDefaultActionColor: '#FFFFFF',
  headerDefaultBorderColor: '#4b4c45',
  headerDefaultLogoColor: '#FFFFFF',
  headerShadowDefault: '0 0.475 0.6 -1.25 #00000014, 0 3.75 5 -1.25 #00000026',
  headerBorderWidth: 1,
  headerBorderRadius: 0,
  headerActionFont: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  headerPrimaryBackgroundColor: '#004180',
  headerPrimaryActionColor: '#FFFFFF',
  headerPrimaryBorderColor: '#004180',
  headerPrimaryLogoColor: '#FFFFFF',
  breakpointsXs: 320,
  breakpointsSm: 576,
  breakpointsMd: 768,
  breakpointsLg: 992,
  breakpointsXl: 1200,
  breakpointsXxl: 1400,
  containersXs: 290,
  containersSm: 540,
  containersMd: 720,
  containersLg: 960,
  containersXl: 1140,
  containersXxl: 1140,
  containersFluid: '100%',
  formInputColor: '#FFFFFF',
  formPlaceholderColor: '#919389',
  formBorderColor: '#4b4c45',
  formBackgroundColor: '#1d1e1b',
  formIconColor: '#ecedec',
  formHintTextColor: '#ecedec',
  formLabelColor: '#FFFFFF',
  formSelectOptionDefaultBackgroundColor: '#2e2f2a',
  formSelectOptionDefaultTextColor: '#FFFFFF',
  formSelectOptionHoverTextColor: '#61B3FF',
  formSelectOptionHoverBackgroundColor: '#004180',
  formSelectOptionBorderRadius: 8,
  formSelectOptionText: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  formSelectOptionPaddingX: 16,
  formSelectOptionPaddingY: 12,
  formSelectOptionActiveTextColor: '#FFFFFF',
  formSelectOptionActiveBackgroundColor: '#4b4c45',
  formSelectOptionShadow:
    '0 0.475 0.6 -1.25 #00000014, 0 3.75 5 -1.25 #00000026',
  formDisabledLabelColor: '#acaea7',
  formDisabledInputColor: '#acaea7',
  formDisabledHintColor: '#acaea7',
  formDisabledIconColor: '#919389',
  formDisabledBackgroundColor: '#2e2f2a',
  formDisabledBorderColor: '#4b4c45',
  formErrorHintText: '#DF7C7C',
  formErrorBorderColor: '#DF7C7C',
  formErrorIconColor: '#DF7C7C',
  formSuccessIconColor: '#3AF789',
  formFocusBorderColor: '#61B3FF',
  formCheckRadioDefault: '#61B3FF',
  formCheckRadioHover: '#007BF0',
  formCheckRadioSizeDefault: 22,
  formCheckRadioSizeInside: 8,
  formCheckRadioGap: 8,
  formPinSizeDefault: 44,
  formPinSizeSmall: 32,
  formPinSizeLarge: 52,
  formInputBorderRadius: 4,
  formInputBorderWidth: 1,
  formInputTextSmall: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 16,
    fontSize: 13,
  },
  formInputTextMedium: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  formInputTextLarge: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 20,
  },
  formInputTextLabel: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 16,
    fontSize: 13,
  },
  formInputTextGap: 10,
  formInputSmallPaddingX: 8,
  formInputSmallPaddingY: 8,
  formInputMediumPaddingX: 16,
  formInputMediumPaddingY: 12,
  formInputLargePaddingX: 24,
  formInputLargePaddingY: 16,
  formInputGap: 5,
  formHintText: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 12,
    fontSize: 10,
  },
  formBorderRadiusNone: 0,
  formSelectArrow:
    "url(\"data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3e%3cpath fill='none' stroke='white' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='m2 5 6 6 6-6'/%3e%3c/svg%3e\")",
  formCheckRadioLabel: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  formInputGroupTextSmall: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 16,
    fontSize: 13,
  },
  formInputGroupTextMedium: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  formInputGroupTextLarge: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 20,
  },
  formRadioButtonDefaultLabelColor: '#61B3FF',
  formRadioButtonDefaultBorderColor: '#61B3FF',
  formRadioButtonDefaultIconColor: '#61B3FF',
  formRadioButtonDefaultBackgroundColor: '#00000000',
  formRadioButtonActiveLabelColor: '#ecedec',
  formRadioButtonActiveBorderColor: '#4b4c45',
  formRadioButtonActiveIconColor: '#ecedec',
  formRadioButtonActiveBackgroundColor: '#4b4c45',
  formRadioButtonHoverLabelColor: '#61B3FF',
  formRadioButtonHoverBorderColor: '#61B3FF',
  formRadioButtonHoverIconColor: '#61B3FF',
  formRadioButtonHoverBackgroundColor: '#004180',
  formRadioButtonText: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  radioButtonBorderRadius: 8,
  dropdownBackgroundColor: '#2e2f2a',
  dropdownBorderColor: '#4b4c45',
  dropdownNoBackground: '#00000000',
  dropdownUnderlineColor: '#4b4c45',
  dropdownActionColor: '#FFFFFF',
  dropdownTextColor: '#FFFFFF',
  dropdownHoverBackgroundColor: '#004180',
  dropdownHoverActionColor: '#61B3FF',
  dropdownActiveBackgroundColor: '#4b4c45',
  dropdownDisabledActionColor: '#919389',
  dropdownBorderRadius: 4,
  dropdownShadow: '0 0.475 0.6 -1.25 #00000014, 0 3.75 5 -1.25 #00000026',
  dropdownNoShadow: '0 0 0 0 #00000000',
  dropdownBorderWidth: 1,
  dropdownNoBorder: 0,
  dropdownPaddingY: 12,
  dropdownPaddingX: 16,
  dropdownFont: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    fontSize: 16,
    lineHeight: 20,
  },
  dropdownDividerPaddingY: 6,
  cardBackgroundColor: '#2e2f2a',
  cardHeaderColor: '#FFFFFF',
  cardHeaderColorLink: '#61B3FF',
  cardSubheadColor: '#FFFFFF',
  cardBodyColor: '#FFFFFF',
  cardBorderColor: '#4b4c45',
  cardBorderRadius: 8,
  cardShadow: '0 0.475 0.6 -1.25 #00000014, 0 3.75 5 -1.25 #00000026',
  cardBorderWidth: 1,
  cardHeaderDefault: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 28,
    fontSize: 25,
  },
  cardHeaderSmall: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 20,
  },
  cardSubhead: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 20,
  },
  cardBodyDefault: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    fontSize: 16,
    lineHeight: 20,
  },
  cardBodySmall: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    fontSize: 13,
    lineHeight: 16,
  },
  cardPaddingX: 16,
  cardPaddingY: 16,
  buttonPrimaryDefaultBackgroundColor: '#61B3FF',
  buttonPrimaryDefaultTextColor: '#000000',
  buttonPrimaryDefaultIconColor: '#000000',
  buttonPrimaryDefaultBorderColor: '#61B3FF',
  buttonPrimaryHoverBackgroundColor: '#007BF0',
  buttonPrimaryHoverTextColor: '#000000',
  buttonPrimaryHoverIconColor: '#000000',
  buttonPrimaryHoverBorderColor: '#007BF0',
  buttonPrimaryDisabledBackgroundColor: '#919389',
  buttonPrimaryDisabledTextColor: '#2e2f2a',
  buttonPrimaryDisabledIconColor: '#2e2f2a',
  buttonPrimaryDisabledBorderColor: '#919389',
  buttonPrimaryBorderRadius: 8,
  buttonPrimarySmallPaddingX: 8,
  buttonPrimarySmallPaddingY: 8,
  buttonPrimaryMediumPaddingX: 16,
  buttonPrimaryMediumPaddingY: 12,
  buttonPrimaryLargePaddingX: 24,
  buttonPrimaryLargePaddingY: 16,
  buttonPrimaryBorderWidth: 1,
  buttonPrimaryUnderline: 0,
  buttonSecondaryDefaultBackgroundColor: '#00000000',
  buttonSecondaryDefaultTextColor: '#61B3FF',
  buttonSecondaryDefaultIconColor: '#61B3FF',
  buttonSecondaryDefaultBorderColor: '#61B3FF',
  buttonSecondaryHoverBackgroundColor: '#00000000',
  buttonSecondaryHoverTextColor: '#007BF0',
  buttonSecondaryHoverIconColor: '#007BF0',
  buttonSecondaryHoverBorderColor: '#007BF0',
  buttonSecondaryDisabledBackgroundColor: '#00000000',
  buttonSecondaryDisabledTextColor: '#919389',
  buttonSecondaryDisabledIconColor: '#919389',
  buttonSecondaryDisabledBorderColor: '#919389',
  buttonSecondaryBorderRadius: 8,
  buttonSecondarySmallPaddingX: 8,
  buttonSecondarySmallPaddingY: 8,
  buttonSecondaryMediumPaddingX: 16,
  buttonSecondaryMediumPaddingY: 12,
  buttonSecondaryLargePaddingX: 24,
  buttonSecondaryLargePaddingY: 16,
  buttonSecondaryBorderWidth: 1,
  buttonSecondaryUnderline: 0,
  buttonTertiaryDefaultBackgroundColor: '#00000000',
  buttonTertiaryDefaultTextColor: '#61B3FF',
  buttonTertiaryDefaultIconColor: '#61B3FF',
  buttonTertiaryDefaultBorderColor: '#61B3FF',
  buttonTertiaryHoverBackgroundColor: '#00000000',
  buttonTertiaryHoverTextColor: '#007BF0',
  buttonTertiaryHoverIconColor: '#007BF0',
  buttonTertiaryHoverBorderColor: '#007BF0',
  buttonTertiaryDisabledBackgroundColor: '#00000000',
  buttonTertiaryDisabledTextColor: '#919389',
  buttonTertiaryDisabledIconColor: '#919389',
  buttonTertiaryDisabledBorderColor: '#919389',
  buttonTertiaryBorderRadius: 0,
  buttonTertiarySmallPaddingX: 0,
  buttonTertiarySmallPaddingY: 8,
  buttonTertiaryMediumPaddingX: 0,
  buttonTertiaryMediumPaddingY: 8,
  buttonTertiaryLargePaddingX: 0,
  buttonTertiaryLargePaddingY: 8,
  buttonTertiaryBorderWidth: 0,
  buttonTertiaryUnderline: 1,
  buttonSmallFont: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 16,
    fontSize: 13,
  },
  buttonMediumFont: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  buttonLargeFont: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 20,
  },
  buttonShadowActive: '0 0.475 0.6 -1.25 #00000014, 0 3.75 5 -1.25 #00000026',
  buttonCtaPrimaryDefaultBackgroundColor: '#FFDD8A',
  buttonCtaPrimaryDefaultTextColor: '#000000',
  buttonCtaPrimaryDefaultIconColor: '#000000',
  buttonCtaPrimaryDefaultBorderColor: '#FFDD8A',
  buttonCtaPrimaryHoverBackgroundColor: '#f7d247',
  buttonCtaPrimaryHoverTextColor: '#000000',
  buttonCtaPrimaryHoverIconColor: '#000000',
  buttonCtaPrimaryHoverBorderColor: '#f7d247',
  buttonCtaPrimaryDisabledBackgroundColor: '#919389',
  buttonCtaPrimaryDisabledTextColor: '#2e2f2a',
  buttonCtaPrimaryDisabledIconColor: '#2e2f2a',
  buttonCtaPrimaryDisabledBorderColor: '#919389',
  buttonWhitePrimaryDefaultBackgroundColor: '#FFFFFF',
  buttonWhitePrimaryDefaultTextColor: '#000000',
  buttonWhitePrimaryDefaultIconColor: '#000000',
  buttonWhitePrimaryDefaultBorderColor: '#FFFFFF',
  buttonWhitePrimaryHoverBackgroundColor: '#f6f6f5',
  buttonWhitePrimaryHoverTextColor: '#000000',
  buttonWhitePrimaryHoverIconColor: '#000000',
  buttonWhitePrimaryHoverBorderColor: '#f6f6f5',
  buttonWhitePrimaryDisabledBackgroundColor: '#ffffff80',
  buttonWhitePrimaryDisabledTextColor: '#00000080',
  buttonWhitePrimaryDisabledIconColor: '#00000080',
  buttonWhitePrimaryDisabledBorderColor: '#ffffff80',
  buttonWhiteSecondaryDefaultBackgroundColor: '#00000000',
  buttonWhiteSecondaryDefaultTextColor: '#FFFFFF',
  buttonWhiteSecondaryDefaultIconColor: '#FFFFFF',
  buttonWhiteSecondaryDefaultBorderColor: '#FFFFFF',
  buttonWhiteSecondaryHoverBackgroundColor: '#00000000',
  buttonWhiteSecondaryHoverTextColor: '#f6f6f5',
  buttonWhiteSecondaryHoverIconColor: '#f6f6f5',
  buttonWhiteSecondaryHoverBorderColor: '#f6f6f5',
  buttonWhiteSecondaryDisabledBackgroundColor: '#00000000',
  buttonWhiteSecondaryDisabledTextColor: '#ffffff80',
  buttonWhiteSecondaryDisabledIconColor: '#ffffff80',
  buttonWhiteSecondaryDisabledBorderColor: '#ffffff80',
  buttonWhiteTertiaryDefaultBackgroundColor: '#00000000',
  buttonWhiteTertiaryDefaultTextColor: '#FFFFFF',
  buttonWhiteTertiaryDefaultIconColor: '#FFFFFF',
  buttonWhiteTertiaryDefaultBorderColor: '#FFFFFF',
  buttonWhiteTertiaryHoverBackgroundColor: '#00000000',
  buttonWhiteTertiaryHoverTextColor: '#f6f6f5',
  buttonWhiteTertiaryHoverIconColor: '#f6f6f5',
  buttonWhiteTertiaryHoverBorderColor: '#f6f6f5',
  buttonWhiteTertiaryDisabledBackgroundColor: '#00000000',
  buttonWhiteTertiaryDisabledTextColor: '#ffffff80',
  buttonWhiteTertiaryDisabledIconColor: '#ffffff80',
  buttonWhiteTertiaryDisabledBorderColor: '#ffffff80',
  buttonInversePrimaryDefaultBackgroundColor: '#FFFFFF',
  buttonInversePrimaryDefaultTextColor: '#000000',
  buttonInversePrimaryDefaultIconColor: '#000000',
  buttonInversePrimaryDefaultBorderColor: '#FFFFFF',
  buttonInversePrimaryHoverBackgroundColor: '#e2e2e2',
  buttonInversePrimaryHoverTextColor: '#000000',
  buttonInversePrimaryHoverIconColor: '#000000',
  buttonInversePrimaryHoverBorderColor: '#e2e2e2',
  buttonInversePrimaryDisabledBackgroundColor: '#ffffff80',
  buttonInversePrimaryDisabledTextColor: '#00000080',
  buttonInversePrimaryDisabledIconColor: '#00000080',
  buttonInversePrimaryDisabledBorderColor: '#ffffff80',
  buttonInverseSecondaryDefaultBackgroundColor: '#00000000',
  buttonInverseSecondaryDefaultTextColor: '#FFFFFF',
  buttonInverseSecondaryDefaultIconColor: '#FFFFFF',
  buttonInverseSecondaryDefaultBorderColor: '#FFFFFF',
  buttonInverseSecondaryHoverBackgroundColor: '#00000000',
  buttonInverseSecondaryHoverTextColor: '#e2e2e2',
  buttonInverseSecondaryHoverIconColor: '#e2e2e2',
  buttonInverseSecondaryHoverBorderColor: '#e2e2e2',
  buttonInverseSecondaryDisabledBackgroundColor: '#00000000',
  buttonInverseSecondaryDisabledTextColor: '#ffffff80',
  buttonInverseSecondaryDisabledIconColor: '#ffffff80',
  buttonInverseSecondaryDisabledBorderColor: '#ffffff80',
  buttonInverseTertiaryDefaultBackgroundColor: '#00000000',
  buttonInverseTertiaryDefaultTextColor: '#FFFFFF',
  buttonInverseTertiaryDefaultIconColor: '#FFFFFF',
  buttonInverseTertiaryDefaultBorderColor: '#FFFFFF',
  buttonInverseTertiaryHoverBackgroundColor: '#00000000',
  buttonInverseTertiaryHoverTextColor: '#e2e2e2',
  buttonInverseTertiaryHoverIconColor: '#e2e2e2',
  buttonInverseTertiaryHoverBorderColor: '#e2e2e2',
  buttonInverseTertiaryDisabledBackgroundColor: '#00000000',
  buttonInverseTertiaryDisabledTextColor: '#ffffff80',
  buttonInverseTertiaryDisabledIconColor: '#ffffff80',
  buttonInverseTertiaryDisabledBorderColor: '#ffffff80',
  buttonDestructiveSecondaryDefaultBackgroundColor: '#00000000',
  buttonDestructiveSecondaryDefaultTextColor: '#DF7C7C',
  buttonDestructiveSecondaryDefaultIconColor: '#DF7C7C',
  buttonDestructiveSecondaryDefaultBorderColor: '#DF7C7C',
  buttonDestructiveSecondaryHoverBackgroundColor: '#00000000',
  buttonDestructiveSecondaryHoverTextColor: '#D75B5B',
  buttonDestructiveSecondaryHoverIconColor: '#D75B5B',
  buttonDestructiveSecondaryHoverBorderColor: '#D75B5B',
  buttonDestructiveTertiaryDefaultBackgroundColor: '#00000000',
  buttonDestructiveTertiaryDefaultTextColor: '#DF7C7C',
  buttonDestructiveTertiaryDefaultIconColor: '#DF7C7C',
  buttonDestructiveTertiaryDefaultBorderColor: '#DF7C7C',
  buttonDestructiveTertiaryHoverBackgroundColor: '#00000000',
  buttonDestructiveTertiaryHoverTextColor: '#D75B5B',
  buttonDestructiveTertiaryHoverIconColor: '#D75B5B',
  buttonDestructiveTertiaryHoverBorderColor: '#D75B5B',
  buttonGap: 10,
  breadcrumbDividerColor: '#919389',
  breadcrumbActionColor: '#61B3FF',
  breadcrumbActiveActionColor: '#ecedec',
  breadcrumbMdFont: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  breadcrumbSmFont: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 16,
    fontSize: 13,
  },
  borderColorNeutral: '#4b4c45',
  borderColorPrimary: '#61B3FF',
  borderRadiusNone: 0,
  borderRadiusRounded: 8,
  borderRadiusCircle: 512,
  borderWidthDefault: 1,
  borderWidthNone: 0,
  badgePrimaryBackgroundColor: '#61B3FF',
  badgePrimaryTextColor: '#000000',
  badgePrimaryIconColor: '#000000',
  badgePrimaryBorderColor: '#61B3FF',
  badgePaddingX: 4,
  badgePaddingY: 4,
  badgeBorderRadius: 4,
  badgeBorderRadiusPill: 512,
  badgeBorderWidth: 1,
  badgeDangerBackgroundColor: '#DF7C7C',
  badgeDangerTextColor: '#000000',
  badgeDangerIconColor: '#000000',
  badgeDangerBorderColor: '#DF7C7C',
  badgeWarningBackgroundColor: '#FFD05C',
  badgeWarningTextColor: '#000000',
  badgeWarningIconColor: '#000000',
  badgeWarningBorderColor: '#FFD05C',
  badgeSuccessBackgroundColor: '#3AF789',
  badgeSuccessTextColor: '#000000',
  badgeSuccessIconColor: '#000000',
  badgeSuccessBorderColor: '#3AF789',
  badgeInfoBackgroundColor: '#87DBFF',
  badgeInfoTextColor: '#000000',
  badgeInfoIconColor: '#000000',
  badgeInfoBorderColor: '#87DBFF',
  badgeNeutralBackgroundColor: '#4b4c45',
  badgeNeutralTextColor: '#FFFFFF',
  badgeNeutralIconColor: '#FFFFFF',
  badgeNeutralBorderColor: '#4b4c45',
  badgeFont: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 13,
    fontSize: 10,
  },
  backgroundPrimaryDefault: '#004180',
  backgroundPrimarySubtle: '#002448',
  backgroundPrimaryAmplified: '#005EB8',
  backgroundAccentDefault: '#8F6500',
  backgroundAccentSubtle: '#573E00',
  backgroundAccentAmplified: '#C78D00',
  backgroundSecondaryDefault: '#004663',
  backgroundSecondarySubtle: '#002535',
  backgroundSecondaryAmplified: '#006691',
  backgroundNeutralSubtle: '#2e2f2a',
  backgroundNeutralDefault: '#1d1e1b',
  backgroundNeutralAmplified: '#4b4c45',
  alertPrimaryBackgroundColor: '#004180',
  alertPrimaryBodyColor: '#D2E9FF',
  alertPrimaryBorderColor: '#61B3FF',
  alertPrimaryHeaderColor: '#D2E9FF',
  alertPrimaryIconColor: '#D2E9FF',
  alertDangerBackgroundColor: '#5B1616',
  alertDangerBodyColor: '#EBADAD',
  alertDangerBorderColor: '#DF7C7C',
  alertDangerHeaderColor: '#EBADAD',
  alertDangerIconColor: '#EBADAD',
  alertSuccessBackgroundColor: '#035827',
  alertSuccessBodyColor: '#E6FEF0',
  alertSuccessBorderColor: '#3AF789',
  alertSuccessHeaderColor: '#E6FEF0',
  alertSuccessIconColor: '#E6FEF0',
  alertWarningBackgroundColor: '#573E00',
  alertWarningBodyColor: '#FFF1CF',
  alertWarningBorderColor: '#FFD05C',
  alertWarningHeaderColor: '#FFF1CF',
  alertWarningIconColor: '#FFF1CF',
  alertBorderRadius: 8,
  alertShadow: '0 0.95 1.55 -2.5 #00000012, 0 7.5 12.5 -2.5 #00000024',
  alertNeutralBackgroundColor: '#4b4c45',
  alertNeutralBodyColor: '#FFFFFF',
  alertNeutralBorderColor: '#ecedec',
  alertNeutralHeaderColor: '#FFFFFF',
  alertNeutralIconColor: '#FFFFFF',
  alertHeaderFont: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 20,
  },
  alertBodyFont: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  alertPaddingX: 16,
  alertPaddingY: 16,
  alertCloseColor: '#FFFFFF',
  accordionBackgroundColor: '#2e2f2a',
  accordionBorderColor: '#4b4c45',
  accordionUnderlineColor: '#4b4c45',
  accordionActionColor: '#61B3FF',
  accordionBodyColor: '#FFFFFF',
  accordionHoverBackgroundColor: '#004180',
  accordionActiveBackgroundColor: '#4b4c45',
  accordionActiveActionColor: '#ecedec',
  accordionDisabledBackgroundColor: '#2e2f2a',
  accordionDisabledActionColor: '#919389',
  accordionBorderRadius: 8,
  accordionBorderWidth: 1,
  accordionNoBorder: 0,
  accordionPaddingX: 16,
  accordionPaddingY: 12,
  accordionLinkFont: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  accordionBodyFont: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
};
