export interface CdsTokens {
  [key: string]: number | string | CdsTokens;
}

export const cdsLightTokens = {
  typeHeadingH1DesktopRegular: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 52,
    fontSize: 49,
  },
  typeHeadingH1DesktopBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 52,
    fontSize: 49,
  },
  typeHeadingH1MobileRegular: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 32,
    fontSize: 31,
  },
  typeHeadingH1MobileBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 32,
    fontSize: 31,
  },
  typeHeadingH2DesktopRegular: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 40,
    fontSize: 39,
  },
  typeHeadingH2DesktopBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 40,
    fontSize: 39,
  },
  typeHeadingH2MobileRegular: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 32,
    fontSize: 31,
  },
  typeHeadingH2MobileBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 32,
    fontSize: 31,
  },
  typeHeadingH3DesktopRegular: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 32,
    fontSize: 31,
  },
  typeHeadingH3DesktopBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 32,
    fontSize: 31,
  },
  typeHeadingH3MobileRegular: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 28,
    fontSize: 25,
  },
  typeHeadingH3MobileBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 28,
    fontSize: 25,
  },
  typeHeadingH4DesktopRegular: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 28,
    fontSize: 25,
  },
  typeHeadingH4DesktopBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 28,
    fontSize: 25,
  },
  typeHeadingH4MobileRegular: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 20,
  },
  typeHeadingH4MobileBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 20,
  },
  typeHeadingH5DesktopRegular: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 20,
  },
  typeHeadingH5DesktopBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 20,
  },
  typeHeadingH5MobileRegular: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  typeHeadingH5MobileBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  typeHeadingH6DesktopRegular: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  typeHeadingH6DesktopBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  typeHeadingH6MobileRegular: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  typeHeadingH6MobileBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  typeHeadingRegular: { fontFamily: 'Gotham-Book', fontWeight: 'normal' },
  typeHeadingSemibold: { fontFamily: 'Gotham-Medium', fontWeight: 'normal' },
  typeHeadingBold: { fontFamily: 'Gotham-Bold', fontWeight: 'normal' },
  typeBodyPDesktopRegular: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  typeBodyPDesktopBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  typeBodyPMobileRegular: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  typeBodyPMobileBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  typeBodyPSmallDesktopRegular: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 16,
    fontSize: 13,
  },
  typeBodyPSmallDesktopBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 16,
    fontSize: 13,
  },
  typeBodyPSmallMobileRegular: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 16,
    fontSize: 13,
  },
  typeBodyPSmallMobileBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 16,
    fontSize: 13,
  },
  typeBodyRegular: { fontFamily: 'Gotham-Book', fontWeight: 'normal' },
  typeBodySemibold: { fontFamily: 'Gotham-Medium', fontWeight: 'normal' },
  typeBodyBold: { fontFamily: 'Gotham-Bold', fontWeight: 'normal' },
  typeColor: '#2e2f2a',
  typeColorWhite: '#FFFFFF',
  typeColorAccent: '#FFB500',
  typeColorPrimary: '#005EB8',
  typeCaseUppercase: 'uppercase',
  typeMarginBottomDesktop: 16,
  typeMarginBottomMobile: 16,
  tooltipPaddingX: 8,
  tooltipPaddingY: 4,
  tooltipBorderRadius: 4,
  tooltipBorderWidth: 1,
  tooltipFont: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 13,
    fontSize: 10,
  },
  tooltipBackgroundColor: '#000000',
  tooltipBorderColor: '#000000',
  tooltipTextColor: '#FFFFFF',
  toastBackgroundColor: '#FFFFFF',
  toastBodyColor: '#2e2f2a',
  toastBorderColor: '#e3e4e2',
  toastActionColor: '#005EB8',
  toastBorderRadius: 8,
  toastShadow: '0 0.95 1.55 -2.5 #00000012, 0 7.5 12.5 -2.5 #00000024',
  toastButtonFont: {
    fontSize: 16,
    letterSpacing: '',
    lineHeight: 20,
    fontWeight: 'normal',
    fontFamily: 'Gotham-Bold',
  },
  tableBackgroundColor: '#FFFFFF',
  tableBorderColor: '#e3e4e2',
  tableNoBackground: '#00000000',
  tableHeaderColor: '#000000',
  tableTextColor: '#000000',
  tableActionColor: '#005EB8',
  tableHoverBackgroundColor: '#D2E9FF',
  tableActiveBackgroundColor: '#e3e4e2',
  tableActiveActionColor: '#4b4c45',
  tableDisabledBackgroundColor: '#f6f6f5',
  tableDisabledActionColor: '#acaea7',
  tableDisabledHeaderColor: '#686a60',
  tableDisabledTextColor: '#686a60',
  tableBorderRadius: 0,
  tableBorderWidth: 1,
  tableNoBorder: 0,
  tableHeaderFont: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  tableCellFont: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  tabBackgroundColor: '#FFFFFF',
  tabBorderColor: '#e3e4e2',
  tabNoBackground: '#00000000',
  tabUnderlineColor: '#c8c9c4',
  tabActionColor: '#005EB8',
  tabHoverBackgroundColor: '#D2E9FF',
  tabActiveBackgroundColor: '#e3e4e2',
  tabActiveActionColor: '#4b4c45',
  tabDisabledBackgroundColor: '#f6f6f5',
  tabDisabledActionColor: '#acaea7',
  tabBorderRadius: 4,
  tabShadow: '0 0.475 0.6 -1.25 #00000014, 0 3.75 5 -1.25 #00000026',
  tabNoShadow: '0 0 0 0 #00000000',
  tabBorderWidth: 1,
  tabNoBorder: 0,
  tabPaddingX: 16,
  tabPaddingY: 12,
  tabFont: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  margin1: 8,
  margin2: 12,
  margin3: 16,
  margin4: 24,
  margin5: 32,
  padding1: 8,
  padding2: 12,
  padding3: 16,
  padding4: 24,
  padding5: 32,
  progressLabel: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 16,
    fontSize: 13,
  },
  progressProgressColor: '#005EB8',
  progressBackgroundColor: '#e3e4e2',
  progressLabelColor: '#2e2f2a',
  progressDefaultHeight: 8,
  progressSmallHeight: 4,
  progressLargeHeight: 12,
  paginationBackgroundColor: '#FFFFFF',
  paginationBorderColor: '#e3e4e2',
  paginationActionColor: '#005EB8',
  paginationHoverBackgroundColor: '#D2E9FF',
  paginationActiveBackgroundColor: '#e3e4e2',
  paginationActiveActionColor: '#4b4c45',
  paginationDisabledBackgroundColor: '#f6f6f5',
  paginationDisabledActionColor: '#acaea7',
  paginationBorderRadius: 8,
  paginationShadow: '0 0.475 0.6 -1.25 #00000014, 0 3.75 5 -1.25 #00000026',
  paginationMdPaddingX: 16,
  paginationMdPaddingY: 12,
  paginationMdFont: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  paginationSmFont: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 16,
    fontSize: 13,
  },
  paginationSmPaddingX: 12,
  paginationSmPaddingY: 8,
  paginationLgFont: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 20,
  },
  paginationLgPaddingX: 16,
  paginationLgPaddingY: 12,
  navBackgroundColor: '#FFFFFF',
  navBorderColor: '#e3e4e2',
  navUnderlineColor: '#c8c9c4',
  navActionColor: '#005EB8',
  navHoverBackgroundColor: '#D2E9FF',
  navActiveBackgroundColor: '#e3e4e2',
  navActiveActionColor: '#4b4c45',
  navDisabledBackgroundColor: '#f6f6f5',
  navDisabledActionColor: '#acaea7',
  navBorderWidth: 1,
  navNoBorder: 0,
  navPaddingX: 16,
  navPaddingY: 12,
  navLinkFont: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  navSubnavLinkFont: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 16,
    fontSize: 13,
  },
  modalBorderRadius: 8,
  modalShadow: '0 0.95 1.55 -2.5 #00000012, 0 7.5 12.5 -2.5 #00000024',
  modalBackgroundColor: '#FFFFFF',
  modalHeaderColor: '#2e2f2a',
  modalBodyColor: '#2e2f2a',
  modalBorderColor: '#e3e4e2',
  modalHeaderFont: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    fontSize: 25,
    lineHeight: 28,
  },
  modalBodyFont: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  modalDefaultMaxWidth: 660,
  modalSmallMaxWidth: 320,
  modalWideMaxWidth: 990,
  listGroupBackgroundColor: '#FFFFFF',
  listGroupBorderColor: '#e3e4e2',
  listGroupUnderlineColor: '#c8c9c4',
  listGroupIconColor: '#005EB8',
  listGroupBodyColor: '#2e2f2a',
  listGroupHeadingColor: '#2e2f2a',
  listGroupHoverBackgroundColor: '#D2E9FF',
  listGroupActiveBackgroundColor: '#e3e4e2',
  listGroupActiveIconColor: '#4b4c45',
  listGroupActiveHeadingColor: '#4b4c45',
  listGroupActiveBodyColor: '#4b4c45',
  listGroupDisabledBackgroundColor: '#f6f6f5',
  listGroupDisabledHeadingColor: '#acaea7',
  listGroupDisabledBodyColor: '#acaea7',
  listGroupDisabledIconColor: '#acaea7',
  listGroupBorderRadius: 8,
  listGroupBorderWidth: 1,
  listGroupNoBorder: 0,
  listGroupPaddingX: 16,
  listGroupPaddingY: 12,
  listGroupHeadingFont: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  listGroupActionFont: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  listGroupBodyFont: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  listGroupImageBorderRadiusDefault: 0,
  listGroupImageBorderRadiusRounded: 8,
  listGroupImageBorderRadiusCircle: 512,
  linkColorDefault: '#005EB8',
  linkColorWhite: '#FFFFFF',
  linkTextDecorationUnderline: 'underline',
  linkFontDefault: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  linkFontBold: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  imageBackgroundColor: '#e3e4e2',
  imageIconColor: '#acaea7',
  imageIconColorInverse: '#FFFFFF',
  iconColorDefault: '#000000',
  iconColorMuted: '#4b4c45',
  iconColorPrimary: '#005EB8',
  iconColorWhite: '#FFFFFF',
  headerDefaultBackgroundColor: '#FFFFFF',
  headerDefaultActionColor: '#2e2f2a',
  headerDefaultBorderColor: '#e3e4e2',
  headerDefaultLogoColor: '#005EB8',
  headerShadowDefault: '0 0.475 0.6 -1.25 #00000014, 0 3.75 5 -1.25 #00000026',
  headerBorderWidth: 1,
  headerBorderRadius: 0,
  headerActionFont: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  headerPrimaryBackgroundColor: '#005EB8',
  headerPrimaryActionColor: '#FFFFFF',
  headerPrimaryBorderColor: '#005EB8',
  headerPrimaryLogoColor: '#FFFFFF',
  breakpointsXs: 320,
  breakpointsSm: 576,
  breakpointsMd: 768,
  breakpointsLg: 992,
  breakpointsXl: 1200,
  breakpointsXxl: 1400,
  containersXs: 290,
  containersSm: 540,
  containersMd: 720,
  containersLg: 960,
  containersXl: 1140,
  containersXxl: 1140,
  containersFluid: '100%',
  formInputColor: '#2e2f2a',
  formPlaceholderColor: '#acaea7',
  formBorderColor: '#e3e4e2',
  formBackgroundColor: '#FFFFFF',
  formIconColor: '#4b4c45',
  formHintTextColor: '#4b4c45',
  formLabelColor: '#2e2f2a',
  formSelectOptionDefaultBackgroundColor: '#FFFFFF',
  formSelectOptionDefaultTextColor: '#2e2f2a',
  formSelectOptionHoverTextColor: '#005EB8',
  formSelectOptionHoverBackgroundColor: '#D2E9FF',
  formSelectOptionBorderRadius: 8,
  formSelectOptionText: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  formSelectOptionPaddingX: 16,
  formSelectOptionPaddingY: 12,
  formSelectOptionActiveTextColor: '#2e2f2a',
  formSelectOptionActiveBackgroundColor: '#e3e4e2',
  formSelectOptionShadow:
    '0 0.475 0.6 -1.25 #00000014, 0 3.75 5 -1.25 #00000026',
  formDisabledLabelColor: '#686a60',
  formDisabledInputColor: '#686a60',
  formDisabledHintColor: '#686a60',
  formDisabledIconColor: '#acaea7',
  formDisabledBackgroundColor: '#f6f6f5',
  formDisabledBorderColor: '#e3e4e2',
  formErrorHintText: '#B52C2C',
  formErrorBorderColor: '#B52C2C',
  formErrorIconColor: '#B52C2C',
  formSuccessIconColor: '#069D45',
  formFocusBorderColor: '#005EB8',
  formCheckRadioDefault: '#005EB8',
  formCheckRadioHover: '#0075E4',
  formCheckRadioSizeDefault: 22,
  formCheckRadioSizeInside: 8,
  formCheckRadioGap: 8,
  formPinSizeDefault: 44,
  formPinSizeSmall: 32,
  formPinSizeLarge: 52,
  formInputBorderRadius: 4,
  formInputBorderWidth: 1,
  formInputTextSmall: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 16,
    fontSize: 13,
  },
  formInputTextMedium: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  formInputTextLarge: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 20,
  },
  formInputTextLabel: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 16,
    fontSize: 13,
  },
  formInputTextGap: 10,
  formInputSmallPaddingX: 8,
  formInputSmallPaddingY: 8,
  formInputMediumPaddingX: 16,
  formInputMediumPaddingY: 12,
  formInputLargePaddingX: 24,
  formInputLargePaddingY: 16,
  formInputGap: 5,
  formHintText: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 12,
    fontSize: 10,
  },
  formBorderRadiusNone: 0,
  formSelectArrow:
    "url(\"data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3e%3cpath fill='none' stroke='%23343a40' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='m2 5 6 6 6-6'/%3e%3c/svg%3e\")",
  formCheckRadioLabel: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  formInputGroupTextSmall: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 16,
    fontSize: 13,
  },
  formInputGroupTextMedium: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  formInputGroupTextLarge: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 20,
  },
  formRadioButtonDefaultLabelColor: '#005EB8',
  formRadioButtonDefaultBorderColor: '#005EB8',
  formRadioButtonDefaultIconColor: '#005EB8',
  formRadioButtonDefaultBackgroundColor: '#00000000',
  formRadioButtonActiveLabelColor: '#4b4c45',
  formRadioButtonActiveBorderColor: '#e3e4e2',
  formRadioButtonActiveIconColor: '#4b4c45',
  formRadioButtonActiveBackgroundColor: '#e3e4e2',
  formRadioButtonHoverLabelColor: '#005EB8',
  formRadioButtonHoverBorderColor: '#005EB8',
  formRadioButtonHoverIconColor: '#005EB8',
  formRadioButtonHoverBackgroundColor: '#D2E9FF',
  formRadioButtonText: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  radioButtonBorderRadius: 8,
  dropdownBackgroundColor: '#FFFFFF',
  dropdownBorderColor: '#e3e4e2',
  dropdownNoBackground: '#00000000',
  dropdownUnderlineColor: '#c8c9c4',
  dropdownActionColor: '#2e2f2a',
  dropdownTextColor: '#2e2f2a',
  dropdownHoverBackgroundColor: '#D2E9FF',
  dropdownHoverActionColor: '#005EB8',
  dropdownActiveBackgroundColor: '#e3e4e2',
  dropdownDisabledActionColor: '#acaea7',
  dropdownBorderRadius: 4,
  dropdownShadow: '0 0.475 0.6 -1.25 #00000014, 0 3.75 5 -1.25 #00000026',
  dropdownNoShadow: '0 0 0 0 #00000000',
  dropdownBorderWidth: 1,
  dropdownNoBorder: 0,
  dropdownPaddingY: 12,
  dropdownPaddingX: 16,
  dropdownFont: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    fontSize: 16,
    lineHeight: 20,
  },
  dropdownDividerPaddingY: 6,
  cardBackgroundColor: '#FFFFFF',
  cardHeaderColor: '#2e2f2a',
  cardHeaderColorLink: '#005EB8',
  cardSubheadColor: '#2e2f2a',
  cardBodyColor: '#2e2f2a',
  cardBorderColor: '#e3e4e2',
  cardBorderRadius: 8,
  cardShadow: '0 0.475 0.6 -1.25 #00000014, 0 3.75 5 -1.25 #00000026',
  cardBorderWidth: 1,
  cardHeaderDefault: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 28,
    fontSize: 25,
  },
  cardHeaderSmall: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 20,
  },
  cardSubhead: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 20,
  },
  cardBodyDefault: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    fontSize: 16,
    lineHeight: 20,
  },
  cardBodySmall: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    fontSize: 13,
    lineHeight: 16,
  },
  cardPaddingX: 16,
  cardPaddingY: 16,
  buttonPrimaryDefaultBackgroundColor: '#005EB8',
  buttonPrimaryDefaultTextColor: '#FFFFFF',
  buttonPrimaryDefaultIconColor: '#FFFFFF',
  buttonPrimaryDefaultBorderColor: '#005EB8',
  buttonPrimaryHoverBackgroundColor: '#0075E4',
  buttonPrimaryHoverTextColor: '#FFFFFF',
  buttonPrimaryHoverIconColor: '#FFFFFF',
  buttonPrimaryHoverBorderColor: '#0075E4',
  buttonPrimaryDisabledBackgroundColor: '#acaea7',
  buttonPrimaryDisabledTextColor: '#f6f6f5',
  buttonPrimaryDisabledIconColor: '#f6f6f5',
  buttonPrimaryDisabledBorderColor: '#acaea7',
  buttonPrimaryBorderRadius: 8,
  buttonPrimarySmallPaddingX: 8,
  buttonPrimarySmallPaddingY: 8,
  buttonPrimaryMediumPaddingX: 16,
  buttonPrimaryMediumPaddingY: 12,
  buttonPrimaryLargePaddingX: 24,
  buttonPrimaryLargePaddingY: 16,
  buttonPrimaryBorderWidth: 1,
  buttonPrimaryUnderline: 0,
  buttonSecondaryDefaultBackgroundColor: '#00000000',
  buttonSecondaryDefaultTextColor: '#005EB8',
  buttonSecondaryDefaultIconColor: '#005EB8',
  buttonSecondaryDefaultBorderColor: '#005EB8',
  buttonSecondaryHoverBackgroundColor: '#00000000',
  buttonSecondaryHoverTextColor: '#0075E4',
  buttonSecondaryHoverIconColor: '#0075E4',
  buttonSecondaryHoverBorderColor: '#0075E4',
  buttonSecondaryDisabledBackgroundColor: '#00000000',
  buttonSecondaryDisabledTextColor: '#acaea7',
  buttonSecondaryDisabledIconColor: '#acaea7',
  buttonSecondaryDisabledBorderColor: '#acaea7',
  buttonSecondaryBorderRadius: 8,
  buttonSecondarySmallPaddingX: 8,
  buttonSecondarySmallPaddingY: 8,
  buttonSecondaryMediumPaddingX: 16,
  buttonSecondaryMediumPaddingY: 12,
  buttonSecondaryLargePaddingX: 24,
  buttonSecondaryLargePaddingY: 16,
  buttonSecondaryBorderWidth: 1,
  buttonSecondaryUnderline: 0,
  buttonTertiaryDefaultBackgroundColor: '#00000000',
  buttonTertiaryDefaultTextColor: '#005EB8',
  buttonTertiaryDefaultIconColor: '#005EB8',
  buttonTertiaryDefaultBorderColor: '#005EB8',
  buttonTertiaryHoverBackgroundColor: '#00000000',
  buttonTertiaryHoverTextColor: '#0075E4',
  buttonTertiaryHoverIconColor: '#0075E4',
  buttonTertiaryHoverBorderColor: '#0075E4',
  buttonTertiaryDisabledBackgroundColor: '#00000000',
  buttonTertiaryDisabledTextColor: '#acaea7',
  buttonTertiaryDisabledIconColor: '#acaea7',
  buttonTertiaryDisabledBorderColor: '#acaea7',
  buttonTertiaryBorderRadius: 0,
  buttonTertiarySmallPaddingX: 0,
  buttonTertiarySmallPaddingY: 8,
  buttonTertiaryMediumPaddingX: 0,
  buttonTertiaryMediumPaddingY: 8,
  buttonTertiaryLargePaddingX: 0,
  buttonTertiaryLargePaddingY: 8,
  buttonTertiaryBorderWidth: 0,
  buttonTertiaryUnderline: 1,
  buttonSmallFont: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 16,
    fontSize: 13,
  },
  buttonMediumFont: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  buttonLargeFont: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 20,
  },
  buttonShadowActive: '0 0.475 0.6 -1.25 #00000014, 0 3.75 5 -1.25 #00000026',
  buttonCtaPrimaryDefaultBackgroundColor: '#f7d247',
  buttonCtaPrimaryDefaultTextColor: '#000000',
  buttonCtaPrimaryDefaultIconColor: '#000000',
  buttonCtaPrimaryDefaultBorderColor: '#f7d247',
  buttonCtaPrimaryHoverBackgroundColor: '#FFDD8A',
  buttonCtaPrimaryHoverTextColor: '#000000',
  buttonCtaPrimaryHoverIconColor: '#000000',
  buttonCtaPrimaryHoverBorderColor: '#FFDD8A',
  buttonCtaPrimaryDisabledBackgroundColor: '#acaea7',
  buttonCtaPrimaryDisabledTextColor: '#f6f6f5',
  buttonCtaPrimaryDisabledIconColor: '#f6f6f5',
  buttonCtaPrimaryDisabledBorderColor: '#acaea7',
  buttonWhitePrimaryDefaultBackgroundColor: '#FFFFFF',
  buttonWhitePrimaryDefaultTextColor: '#000000',
  buttonWhitePrimaryDefaultIconColor: '#000000',
  buttonWhitePrimaryDefaultBorderColor: '#FFFFFF',
  buttonWhitePrimaryHoverBackgroundColor: '#f6f6f5',
  buttonWhitePrimaryHoverTextColor: '#000000',
  buttonWhitePrimaryHoverIconColor: '#000000',
  buttonWhitePrimaryHoverBorderColor: '#f6f6f5',
  buttonWhitePrimaryDisabledBackgroundColor: '#ffffff80',
  buttonWhitePrimaryDisabledTextColor: '#00000080',
  buttonWhitePrimaryDisabledIconColor: '#00000080',
  buttonWhitePrimaryDisabledBorderColor: '#ffffff80',
  buttonWhiteSecondaryDefaultBackgroundColor: '#00000000',
  buttonWhiteSecondaryDefaultTextColor: '#FFFFFF',
  buttonWhiteSecondaryDefaultIconColor: '#FFFFFF',
  buttonWhiteSecondaryDefaultBorderColor: '#FFFFFF',
  buttonWhiteSecondaryHoverBackgroundColor: '#00000000',
  buttonWhiteSecondaryHoverTextColor: '#f6f6f5',
  buttonWhiteSecondaryHoverIconColor: '#f6f6f5',
  buttonWhiteSecondaryHoverBorderColor: '#f6f6f5',
  buttonWhiteSecondaryDisabledBackgroundColor: '#00000000',
  buttonWhiteSecondaryDisabledTextColor: '#ffffff80',
  buttonWhiteSecondaryDisabledIconColor: '#ffffff80',
  buttonWhiteSecondaryDisabledBorderColor: '#ffffff80',
  buttonWhiteTertiaryDefaultBackgroundColor: '#00000000',
  buttonWhiteTertiaryDefaultTextColor: '#FFFFFF',
  buttonWhiteTertiaryDefaultIconColor: '#FFFFFF',
  buttonWhiteTertiaryDefaultBorderColor: '#FFFFFF',
  buttonWhiteTertiaryHoverBackgroundColor: '#00000000',
  buttonWhiteTertiaryHoverTextColor: '#f6f6f5',
  buttonWhiteTertiaryHoverIconColor: '#f6f6f5',
  buttonWhiteTertiaryHoverBorderColor: '#f6f6f5',
  buttonWhiteTertiaryDisabledBackgroundColor: '#00000000',
  buttonWhiteTertiaryDisabledTextColor: '#ffffff80',
  buttonWhiteTertiaryDisabledIconColor: '#ffffff80',
  buttonWhiteTertiaryDisabledBorderColor: '#ffffff80',
  buttonInversePrimaryDefaultBackgroundColor: '#000000',
  buttonInversePrimaryDefaultTextColor: '#FFFFFF',
  buttonInversePrimaryDefaultIconColor: '#FFFFFF',
  buttonInversePrimaryDefaultBorderColor: '#000000',
  buttonInversePrimaryHoverBackgroundColor: '#1c1c1c',
  buttonInversePrimaryHoverTextColor: '#FFFFFF',
  buttonInversePrimaryHoverIconColor: '#FFFFFF',
  buttonInversePrimaryHoverBorderColor: '#1c1c1c',
  buttonInversePrimaryDisabledBackgroundColor: '#00000080',
  buttonInversePrimaryDisabledTextColor: '#ffffff80',
  buttonInversePrimaryDisabledIconColor: '#ffffff80',
  buttonInversePrimaryDisabledBorderColor: '#00000080',
  buttonInverseSecondaryDefaultBackgroundColor: '#00000000',
  buttonInverseSecondaryDefaultTextColor: '#000000',
  buttonInverseSecondaryDefaultIconColor: '#000000',
  buttonInverseSecondaryDefaultBorderColor: '#000000',
  buttonInverseSecondaryHoverBackgroundColor: '#00000000',
  buttonInverseSecondaryHoverTextColor: '#1c1c1c',
  buttonInverseSecondaryHoverIconColor: '#1c1c1c',
  buttonInverseSecondaryHoverBorderColor: '#1c1c1c',
  buttonInverseSecondaryDisabledBackgroundColor: '#00000000',
  buttonInverseSecondaryDisabledTextColor: '#00000080',
  buttonInverseSecondaryDisabledIconColor: '#00000080',
  buttonInverseSecondaryDisabledBorderColor: '#00000080',
  buttonInverseTertiaryDefaultBackgroundColor: '#00000000',
  buttonInverseTertiaryDefaultTextColor: '#000000',
  buttonInverseTertiaryDefaultIconColor: '#000000',
  buttonInverseTertiaryDefaultBorderColor: '#000000',
  buttonInverseTertiaryHoverBackgroundColor: '#00000000',
  buttonInverseTertiaryHoverTextColor: '#1c1c1c',
  buttonInverseTertiaryHoverIconColor: '#1c1c1c',
  buttonInverseTertiaryHoverBorderColor: '#1c1c1c',
  buttonInverseTertiaryDisabledBackgroundColor: '#00000000',
  buttonInverseTertiaryDisabledTextColor: '#00000080',
  buttonInverseTertiaryDisabledIconColor: '#00000080',
  buttonInverseTertiaryDisabledBorderColor: '#00000080',
  buttonDestructiveSecondaryDefaultBackgroundColor: '#00000000',
  buttonDestructiveSecondaryDefaultTextColor: '#B52C2C',
  buttonDestructiveSecondaryDefaultIconColor: '#B52C2C',
  buttonDestructiveSecondaryDefaultBorderColor: '#B52C2C',
  buttonDestructiveSecondaryHoverBackgroundColor: '#00000000',
  buttonDestructiveSecondaryHoverTextColor: '#CF3B3B',
  buttonDestructiveSecondaryHoverIconColor: '#CF3B3B',
  buttonDestructiveSecondaryHoverBorderColor: '#CF3B3B',
  buttonDestructiveTertiaryDefaultBackgroundColor: '#00000000',
  buttonDestructiveTertiaryDefaultTextColor: '#B52C2C',
  buttonDestructiveTertiaryDefaultIconColor: '#B52C2C',
  buttonDestructiveTertiaryDefaultBorderColor: '#B52C2C',
  buttonDestructiveTertiaryHoverBackgroundColor: '#00000000',
  buttonDestructiveTertiaryHoverTextColor: '#CF3B3B',
  buttonDestructiveTertiaryHoverIconColor: '#CF3B3B',
  buttonDestructiveTertiaryHoverBorderColor: '#CF3B3B',
  buttonGap: 10,
  breadcrumbDividerColor: '#acaea7',
  breadcrumbActionColor: '#005EB8',
  breadcrumbActiveActionColor: '#4b4c45',
  breadcrumbMdFont: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  breadcrumbSmFont: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 16,
    fontSize: 13,
  },
  borderColorNeutral: '#e3e4e2',
  borderColorPrimary: '#005EB8',
  borderRadiusNone: 0,
  borderRadiusRounded: 8,
  borderRadiusCircle: 512,
  borderWidthDefault: 1,
  borderWidthNone: 0,
  badgePrimaryBackgroundColor: '#005EB8',
  badgePrimaryTextColor: '#FFFFFF',
  badgePrimaryIconColor: '#FFFFFF',
  badgePrimaryBorderColor: '#005EB8',
  badgePaddingX: 4,
  badgePaddingY: 4,
  badgeBorderRadius: 4,
  badgeBorderRadiusPill: 512,
  badgeBorderWidth: 1,
  badgeDangerBackgroundColor: '#B52C2C',
  badgeDangerTextColor: '#FFFFFF',
  badgeDangerIconColor: '#FFFFFF',
  badgeDangerBorderColor: '#B52C2C',
  badgeWarningBackgroundColor: '#FFB500',
  badgeWarningTextColor: '#000000',
  badgeWarningIconColor: '#000000',
  badgeWarningBorderColor: '#FFB500',
  badgeSuccessBackgroundColor: '#069D45',
  badgeSuccessTextColor: '#FFFFFF',
  badgeSuccessIconColor: '#FFFFFF',
  badgeSuccessBorderColor: '#069D45',
  badgeInfoBackgroundColor: '#0086BF',
  badgeInfoTextColor: '#FFFFFF',
  badgeInfoIconColor: '#FFFFFF',
  badgeInfoBorderColor: '#0086BF',
  badgeNeutralBackgroundColor: '#e3e4e2',
  badgeNeutralTextColor: '#2e2f2a',
  badgeNeutralIconColor: '#2e2f2a',
  badgeNeutralBorderColor: '#e3e4e2',
  badgeFont: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 13,
    fontSize: 10,
  },
  backgroundPrimaryDefault: '#005EB8',
  backgroundPrimarySubtle: '#D2E9FF',
  backgroundPrimaryAmplified: '#004180',
  backgroundAccentDefault: '#FFB500',
  backgroundAccentSubtle: '#FFF1CF',
  backgroundAccentAmplified: '#8F6500',
  backgroundSecondaryDefault: '#0086BF',
  backgroundSecondarySubtle: '#C9EFFF',
  backgroundSecondaryAmplified: '#004663',
  backgroundNeutralSubtle: '#FFFFFF',
  backgroundNeutralDefault: '#FFFFFF',
  backgroundNeutralAmplified: '#e3e4e2',
  alertPrimaryBackgroundColor: '#D2E9FF',
  alertPrimaryBodyColor: '#004180',
  alertPrimaryBorderColor: '#005EB8',
  alertPrimaryHeaderColor: '#004180',
  alertPrimaryIconColor: '#004180',
  alertDangerBackgroundColor: '#EBADAD',
  alertDangerBodyColor: '#5B1616',
  alertDangerBorderColor: '#B52C2C',
  alertDangerHeaderColor: '#5B1616',
  alertDangerIconColor: '#5B1616',
  alertSuccessBackgroundColor: '#E6FEF0',
  alertSuccessBodyColor: '#035827',
  alertSuccessBorderColor: '#069D45',
  alertSuccessHeaderColor: '#035827',
  alertSuccessIconColor: '#035827',
  alertWarningBackgroundColor: '#FFF1CF',
  alertWarningBodyColor: '#8F6500',
  alertWarningBorderColor: '#FFB500',
  alertWarningHeaderColor: '#8F6500',
  alertWarningIconColor: '#8F6500',
  alertBorderRadius: 8,
  alertShadow: '0 0.95 1.55 -2.5 #00000012, 0 7.5 12.5 -2.5 #00000024',
  alertNeutralBackgroundColor: '#e3e4e2',
  alertNeutralBodyColor: '#2e2f2a',
  alertNeutralBorderColor: '#4b4c45',
  alertNeutralHeaderColor: '#2e2f2a',
  alertNeutralIconColor: '#2e2f2a',
  alertHeaderFont: {
    fontFamily: 'Gotham-Bold',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 20,
  },
  alertBodyFont: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  alertPaddingX: 16,
  alertPaddingY: 16,
  alertCloseColor: '#2e2f2a',
  accordionBackgroundColor: '#FFFFFF',
  accordionBorderColor: '#e3e4e2',
  accordionUnderlineColor: '#c8c9c4',
  accordionActionColor: '#005EB8',
  accordionBodyColor: '#2e2f2a',
  accordionHoverBackgroundColor: '#D2E9FF',
  accordionActiveBackgroundColor: '#e3e4e2',
  accordionActiveActionColor: '#4b4c45',
  accordionDisabledBackgroundColor: '#f6f6f5',
  accordionDisabledActionColor: '#acaea7',
  accordionBorderRadius: 8,
  accordionBorderWidth: 1,
  accordionNoBorder: 0,
  accordionPaddingX: 16,
  accordionPaddingY: 12,
  accordionLinkFont: {
    fontFamily: 'Gotham-Medium',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
  accordionBodyFont: {
    fontFamily: 'Gotham-Book',
    fontWeight: 'normal',
    lineHeight: 20,
    fontSize: 16,
  },
};
