#!/usr/bin/env node

import svgr from '@svgr/core';
import elements from '@compassion-gds/elements';
import prettier from 'prettier';
import svgo from 'svgo';

import fs from 'fs';
import path from 'path';

const logoSources = elements.logos;

const capitalize = (text) => {
  return text.charAt(0).toUpperCase() + text.slice(1);
};

const header = `
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildLogoComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

import React from 'react';

/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx } from '@emotion/core';
import PropTypes from 'prop-types';
import logoStyles from '../Logo.styles';
`;

const footer = `

COMPONENT_NAME.propTypes = {
  /**
   * A CSS fill color.
   */
  fill: PropTypes.string.isRequired,
  /**
   * Any valid CSS width value.
   */
  width: PropTypes.string,
};

COMPONENT_NAME.defaultProps = {
  fill: 'brand',
  width: '100%',
};

`;

let indexJs = '';

Object.entries(logoSources).forEach((logoSource) => {
  const name = logoSource[0];

  const rawSvg = svgo.optimize(logoSource[1], [
    {
      name: 'removeDesc',
      active: false,
    },
    {
      name: 'removeTitle',
      active: false,
    },
  ]).data;

  const componentName = `${capitalize(name)}`;

  indexJs += `export { default as ${componentName} } from './logos/${componentName}';\n`;

  svgr
    .default(
      rawSvg,
      {
        icon: true,
        outDir: './logos',
        ignoreExisting: true,
        ext: 'jsx',
        svgProps: {
          viewBox: '0 0 512 194',
          fill: '{props.fill}',
          width: '{props.width}',
          height: '100%',
          className: 'gds-logo',
          css: '{logoStyles}',
        },
        svgo: false,
      },
      { componentName }
    )
    .then((jsCode) => {
      const body = jsCode
        .replace(/import \* as React[^\n]+/, '')
        .replace(/\n{1,}/g, '\n');

      const fileContents = `${header}\n${body}\n${footer.replace(
        /COMPONENT_NAME/g,
        componentName
      )}`;

      fs.writeFile(
        `${path.resolve()}/logos/${componentName}.jsx`,
        prettier.format(fileContents, { parser: 'babel' }),
        (err) => {
          if (err) {
            console.error(err);
          }
        }
      );
    });
});

fs.writeFile(`${path.resolve()}/index.js`, indexJs, (err) => {
  if (err) {
    console.error(err);
  }
});
