#!/usr/bin/env node

import fs from 'fs';
import path from 'path';

const header = `// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildIndexJs.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

import raw from 'raw.macro';

const replaceFill = (rawSvg) => {
  return rawSvg.replace('fill="none"', 'fill="currentColor"').replace(/fill="[^"]+"/g, '');
};

`;

const svgFolder = `${path.resolve()}/svg`;

let svgExports = header;

fs.readdir(svgFolder, (err, svgs) => {
  if (err) {
    console.error(err);
  }

  svgs.forEach((svg) => {
    const name = svg.replace(/\.svg/, '');

    svgExports += `export const ${name} = replaceFill(raw('./svg/${svg}'))\n`;
  });

  fs.writeFile(`${path.resolve()}/index.js`, svgExports, (er) => {
    if (er) {
      console.error(er);
    }
  });
});
