// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildIndexJs.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

import raw from 'raw.macro';

const replaceFill = (rawSvg) => {
  return rawSvg.replace('fill="none"', 'fill="currentColor"').replace(/fill="[^"]+"/g, '');
};

export const Accessibility = replaceFill(raw('./svg/Accessibility.svg'))
export const Add = replaceFill(raw('./svg/Add.svg'))
export const AddCircle = replaceFill(raw('./svg/AddCircle.svg'))
export const ArrowClockwise = replaceFill(raw('./svg/ArrowClockwise.svg'))
export const ArrowDown = replaceFill(raw('./svg/ArrowDown.svg'))
export const ArrowLeft = replaceFill(raw('./svg/ArrowLeft.svg'))
export const ArrowRight = replaceFill(raw('./svg/ArrowRight.svg'))
export const ArrowUp = replaceFill(raw('./svg/ArrowUp.svg'))
export const ArrowsLeftRight = replaceFill(raw('./svg/ArrowsLeftRight.svg'))
export const Camera = replaceFill(raw('./svg/Camera.svg'))
export const ChatText = replaceFill(raw('./svg/ChatText.svg'))
export const Check = replaceFill(raw('./svg/Check.svg'))
export const ChevronDown = replaceFill(raw('./svg/ChevronDown.svg'))
export const ChevronLeft = replaceFill(raw('./svg/ChevronLeft.svg'))
export const ChevronRight = replaceFill(raw('./svg/ChevronRight.svg'))
export const ChevronUp = replaceFill(raw('./svg/ChevronUp.svg'))
export const ClockCounterClockwise = replaceFill(raw('./svg/ClockCounterClockwise.svg'))
export const Compass = replaceFill(raw('./svg/Compass.svg'))
export const CreditCard = replaceFill(raw('./svg/CreditCard.svg'))
export const Error = replaceFill(raw('./svg/Error.svg'))
export const Gear = replaceFill(raw('./svg/Gear.svg'))
export const Gift = replaceFill(raw('./svg/Gift.svg'))
export const Globe = replaceFill(raw('./svg/Globe.svg'))
export const Hidden = replaceFill(raw('./svg/Hidden.svg'))
export const Home = replaceFill(raw('./svg/Home.svg'))
export const Info = replaceFill(raw('./svg/Info.svg'))
export const Map = replaceFill(raw('./svg/Map.svg'))
export const Menu = replaceFill(raw('./svg/Menu.svg'))
export const PhotoStack = replaceFill(raw('./svg/PhotoStack.svg'))
export const Pin = replaceFill(raw('./svg/Pin.svg'))
export const PlayCircle = replaceFill(raw('./svg/PlayCircle.svg'))
export const Question = replaceFill(raw('./svg/Question.svg'))
export const Skippy = replaceFill(raw('./svg/Skippy.svg'))
export const Smile = replaceFill(raw('./svg/Smile.svg'))
export const Spinner = replaceFill(raw('./svg/Spinner.svg'))
export const SpinnerGap = replaceFill(raw('./svg/SpinnerGap.svg'))
export const ThumbsUp = replaceFill(raw('./svg/ThumbsUp.svg'))
export const Trash = replaceFill(raw('./svg/Trash.svg'))
export const Upload = replaceFill(raw('./svg/Upload.svg'))
export const User = replaceFill(raw('./svg/User.svg'))
export const Visible = replaceFill(raw('./svg/Visible.svg'))
export const Zoom = replaceFill(raw('./svg/Zoom.svg'))
export const ZoomIn = replaceFill(raw('./svg/ZoomIn.svg'))
export const ZoomOut = replaceFill(raw('./svg/ZoomOut.svg'))
