// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildIconComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
import React from 'react';
import PropTypes from 'prop-types';
import iconStyles from '../Icon.styles';

const SvgArrowRight = (props) => (
  <svg
    width={props.width}
    height={props.height}
    viewBox="0 0 32 32"
    fill={props.fill}
    xmlns="http://www.w3.org/2000/svg"
    className="gds-icon"
    css={iconStyles}
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M28 16a1 1 0 0 1-1 1H5a1 1 0 1 1 0-2h22a1 1 0 0 1 1 1Z"
      fill="#000"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M17.293 25.707a1 1 0 0 1 0-1.414L25.586 16l-8.293-8.293a1 1 0 0 1 1.414-1.414l9 9a1 1 0 0 1 0 1.414l-9 9a1 1 0 0 1-1.414 0Z"
      fill="#000"
    />
  </svg>
);

SvgArrowRight.propTypes = {
  /**
   * A CSS fill color.
   */
  fill: PropTypes.string,

  /**
   * Any valid CSS width value.
   */
  width: PropTypes.string,

  /**
   * Any valid CSS height value.
   */
  height: PropTypes.string,
};
SvgArrowRight.defaultProps = {
  fill: 'currentColor',
  width: '100%',
  height: '100%',
};
export default SvgArrowRight;
