// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildIconComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
import React from 'react';
import PropTypes from 'prop-types';
import iconStyles from '../Icon.styles';

const SvgHome = (props) => (
  <svg
    width={props.width}
    height={props.height}
    viewBox="0 0 32 32"
    fill={props.fill}
    xmlns="http://www.w3.org/2000/svg"
    className="gds-icon"
    css={iconStyles}
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M14.654 3.87a2 2 0 0 1 2.69 0l10.001 9.092a2 2 0 0 1 .655 1.48V27a1 1 0 1 1-2 0V14.442L16 5.35 6 14.442V27a1 1 0 1 1-2 0V14.442a2 2 0 0 1 .655-1.48l9.999-9.091Z"
      fill="#000"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M1 27a1 1 0 0 1 1-1h28a1 1 0 1 1 0 2H2a1 1 0 0 1-1-1Z"
      fill="#000"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M12 18.999a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1v8a1 1 0 1 1-2 0v-7h-4v7a1 1 0 1 1-2 0v-8Z"
      fill="#000"
    />
  </svg>
);

SvgHome.propTypes = {
  /**
   * A CSS fill color.
   */
  fill: PropTypes.string,

  /**
   * Any valid CSS width value.
   */
  width: PropTypes.string,

  /**
   * Any valid CSS height value.
   */
  height: PropTypes.string,
};
SvgHome.defaultProps = {
  fill: 'currentColor',
  width: '100%',
  height: '100%',
};
export default SvgHome;
