// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildIconComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx } from "@emotion/core";
import PropTypes from "prop-types";
import iconStyles from "../Icon.styles";

function IconQuestion(props) {
  return (
    <svg
      width={props.width}
      height={props.height}
      xmlns="http://www.w3.org/2000/svg"
      fill={props.fill}
      className="gds-icon"
      css={iconStyles}
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M16 5C9.925 5 5 9.925 5 16s4.925 11 11 11 11-4.925 11-11S22.075 5 16 5zM3 16C3 8.82 8.82 3 16 3s13 5.82 13 13-5.82 13-13 13S3 23.18 3 16z"
      />
      <path d="M16 24a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3z" />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M14.278 9.343A4.5 4.5 0 1 1 17 17.888v.113a1 1 0 0 1-2 0v-1a1 1 0 0 1 1-1 2.5 2.5 0 1 0-2.5-2.5 1 1 0 0 1-2 0 4.5 4.5 0 0 1 2.778-4.158z"
      />
    </svg>
  );
}
export default IconQuestion;

IconQuestion.propTypes = {
  fill: PropTypes.string,
  width: PropTypes.string,
  height: PropTypes.string,
};

IconQuestion.defaultProps = {
  fill: "currentColor",
  width: "1em",
  height: "1em",
};
