// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildIconComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx } from "@emotion/core";
import PropTypes from "prop-types";
import iconStyles from "../Icon.styles";

function IconThumbsUp(props) {
  return (
    <svg
      width={props.width}
      height={props.height}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 32 32"
      fill={props.fill}
      className="gds-icon"
      css={iconStyles}
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M2.585 12.586A2 2 0 0 1 3.999 12h6a1 1 0 0 1 1 1v13a1 1 0 0 1-1 1H4a2 2 0 0 1-2-2V14a2 2 0 0 1 .586-1.414zM3.999 14v11h5V14H4z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M14.105 2.553A1 1 0 0 1 14.999 2a5 5 0 0 1 5 5v2h6.735a3 3 0 0 1 2.976 3.372l-1.5 12A3 3 0 0 1 25.235 27H9.999a1 1 0 1 1 0-2h15.235a1 1 0 0 0 .992-.876l1.5-12A1.002 1.002 0 0 0 26.734 11h-7.735a1 1 0 0 1-1-1V7a3.001 3.001 0 0 0-2.41-2.942l-4.695 9.39a1 1 0 0 1-1.79-.895l5-10z"
      />
    </svg>
  );
}
export default IconThumbsUp;

IconThumbsUp.propTypes = {
  fill: PropTypes.string,
  width: PropTypes.string,
  height: PropTypes.string,
};

IconThumbsUp.defaultProps = {
  fill: "currentColor",
  width: "1em",
  height: "1em",
};
