// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildIconComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx } from "@emotion/core";
import PropTypes from "prop-types";
import iconStyles from "../Icon.styles";

function IconSpinner(props) {
  return (
    <svg
      width={props.width}
      height={props.height}
      viewBox="0 0 32 32"
      xmlns="http://www.w3.org/2000/svg"
      fill={props.fill}
      className="gds-icon"
      css={iconStyles}
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M16 3C16.5523 3 17 3.44772 17 4V8C17 8.55228 16.5523 9 16 9C15.4477 9 15 8.55228 15 8V4C15 3.44772 15.4477 3 16 3Z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M25.1923 6.8076C25.5828 7.19813 25.5828 7.83129 25.1923 8.22182L22.3638 11.0502C21.9733 11.4408 21.3402 11.4408 20.9496 11.0502C20.5591 10.6597 20.5591 10.0266 20.9496 9.63603L23.7781 6.8076C24.1686 6.41708 24.8017 6.41708 25.1923 6.8076Z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M23 16C23 15.4477 23.4477 15 24 15H28C28.5523 15 29 15.4477 29 16C29 16.5523 28.5523 17 28 17H24C23.4477 17 23 16.5523 23 16Z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M20.9496 20.9498C21.3402 20.5592 21.9733 20.5592 22.3638 20.9498L25.1923 23.7782C25.5828 24.1687 25.5828 24.8019 25.1923 25.1924C24.8017 25.5829 24.1686 25.5829 23.7781 25.1924L20.9496 22.364C20.5591 21.9734 20.5591 21.3403 20.9496 20.9498Z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M16 23C16.5523 23 17 23.4477 17 24V28C17 28.5523 16.5523 29 16 29C15.4477 29 15 28.5523 15 28V24C15 23.4477 15.4477 23 16 23Z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M11.0502 20.9498C11.4407 21.3403 11.4407 21.9734 11.0502 22.364L8.22176 25.1924C7.83123 25.5829 7.19807 25.5829 6.80754 25.1924C6.41702 24.8019 6.41702 24.1687 6.80754 23.7782L9.63597 20.9498C10.0265 20.5592 10.6597 20.5592 11.0502 20.9498Z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M3 16C3 15.4477 3.44772 15 4 15H8C8.55228 15 9 15.4477 9 16C9 16.5523 8.55228 17 8 17H4C3.44772 17 3 16.5523 3 16Z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M6.80754 6.8076C7.19807 6.41708 7.83123 6.41708 8.22176 6.8076L11.0502 9.63603C11.4407 10.0266 11.4407 10.6597 11.0502 11.0502C10.6597 11.4408 10.0265 11.4408 9.63597 11.0502L6.80754 8.22182C6.41702 7.83129 6.41702 7.19813 6.80754 6.8076Z"
      />
    </svg>
  );
}
export default IconSpinner;

IconSpinner.propTypes = {
  fill: PropTypes.string,
  width: PropTypes.string,
  height: PropTypes.string,
};

IconSpinner.defaultProps = {
  fill: "currentColor",
  width: "1em",
  height: "1em",
};
