// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildIconComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

import React from "react";
import PropTypes from "prop-types";
import iconStyles from "../Icon.styles";

function IconGift(props) {
  return (
    <svg
      width={props.width}
      height={props.height}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 32 32"
      fill={props.fill}
      className="gds-icon"
      css={iconStyles}
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M3 11a2 2 0 0 1 2-2h22a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4Zm24 0H5v4h22v-4Z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M6 15a1 1 0 0 1 1 1v9h18v-9a1 1 0 1 1 2 0v9a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2v-9a1 1 0 0 1 1-1Z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M16 9a1 1 0 0 1 1 1v16a1 1 0 1 1-2 0V10a1 1 0 0 1 1-1Z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M12.464 2.294a4 4 0 0 1 2.828 1.17c.514.514.841 1.215 1.06 1.872.225.674.368 1.4.461 2.053A19.454 19.454 0 0 1 17 9.769V9.828h-1v1H15.94l-.15-.003a19.459 19.459 0 0 1-2.231-.184 11.973 11.973 0 0 1-2.053-.46c-.656-.22-1.357-.546-1.871-1.06a4.001 4.001 0 0 1 2.828-6.827ZM11.05 7.707c.193.193.553.397 1.09.576.52.173 1.118.295 1.703.379.4.057.78.094 1.11.12a16.88 16.88 0 0 0-.12-1.11 10.001 10.001 0 0 0-.378-1.704c-.18-.536-.383-.896-.576-1.09m0 0a2 2 0 0 0-2.829 2.83M16 9.827v1a1.001 1.001 0 0 0 1-1h-1Z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M20.375 2.294c-1.06 0-2.076.42-2.826 1.17-.514.513-.84 1.214-1.06 1.87a11.97 11.97 0 0 0-.46 2.052 19.43 19.43 0 0 0-.186 2.38V9.823c0 .001 0 .002.999.002v1h.017l.042-.001.149-.003a19.475 19.475 0 0 0 2.23-.184 11.96 11.96 0 0 0 2.052-.46c.656-.22 1.357-.546 1.87-1.06a4 4 0 0 0-2.827-6.823Zm1.414 5.41c-.193.194-.553.397-1.089.576a9.993 9.993 0 0 1-1.703.379c-.398.056-.78.094-1.108.119.024-.33.062-.71.119-1.109.084-.585.205-1.183.378-1.703.18-.536.383-.895.576-1.089m0 0a2 2 0 0 1 2.827 2.827m-4.947 2.12v1a1 1 0 0 1-1-1h1Z"
      />
    </svg>
  );
}
export default IconGift;

IconGift.propTypes = {
  /**
   * A CSS fill color.
   */
  fill: PropTypes.string,
  /**
   * Any valid CSS width value.
   */
  width: PropTypes.string,
  /**
   * Any valid CSS height value.
   */
  height: PropTypes.string,
};

IconGift.defaultProps = {
  fill: "currentColor",
  width: "100%",
  height: "100%",
};
