// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildIconComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx } from "@emotion/core";
import PropTypes from "prop-types";
import iconStyles from "../Icon.styles";

function IconArrowClockwise(props) {
  return (
    <svg
      width={props.width}
      height={props.height}
      xmlns="http://www.w3.org/2000/svg"
      fill={props.fill}
      className="gds-icon"
      css={iconStyles}
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M28.021 5.464a1 1 0 0 1 1 1v6a1 1 0 0 1-1 1h-6a1 1 0 1 1 0-2h5v-5a1 1 0 0 1 1-1z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M17.95 6.192a10 10 0 1 0 5.121 16.88 1 1 0 1 1 1.414 1.413 12 12 0 1 1 0-16.97l4.243 4.242a1 1 0 0 1-1.414 1.415L23.07 8.929a10 10 0 0 0-5.12-2.737z"
      />
    </svg>
  );
}
export default IconArrowClockwise;

IconArrowClockwise.propTypes = {
  fill: PropTypes.string,
  width: PropTypes.string,
  height: PropTypes.string,
};

IconArrowClockwise.defaultProps = {
  fill: "currentColor",
  width: "1em",
  height: "1em",
};
