// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildIconComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx } from "@emotion/core";
import PropTypes from "prop-types";
import iconStyles from "../Icon.styles";

function IconCreditCard(props) {
  return (
    <svg
      width={props.width}
      height={props.height}
      viewBox="0 0 32 32"
      xmlns="http://www.w3.org/2000/svg"
      fill={props.fill}
      className="gds-icon"
      css={iconStyles}
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M2 8C2 6.89543 2.89543 6 4 6H28C29.1046 6 30 6.89543 30 8V24C30 25.1046 29.1046 26 28 26H4C2.89543 26 2 25.1046 2 24V8ZM28 8H4V24H28V8Z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M19.9993 21C19.9993 20.4477 20.447 20 20.9993 20H24.9993C25.5516 20 25.9993 20.4477 25.9993 21C25.9993 21.5523 25.5516 22 24.9993 22H20.9993C20.447 22 19.9993 21.5523 19.9993 21Z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M13.9993 21C13.9993 20.4477 14.447 20 14.9993 20H16.9993C17.5516 20 17.9993 20.4477 17.9993 21C17.9993 21.5523 17.5516 22 16.9993 22H14.9993C14.447 22 13.9993 21.5523 13.9993 21Z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M1.99927 12.1065C1.99927 11.5543 2.44698 11.1065 2.99927 11.1065H28.9993C29.5515 11.1065 29.9993 11.5543 29.9993 12.1065C29.9993 12.6588 29.5515 13.1065 28.9993 13.1065H2.99927C2.44698 13.1065 1.99927 12.6588 1.99927 12.1065Z"
      />
    </svg>
  );
}
export default IconCreditCard;

IconCreditCard.propTypes = {
  fill: PropTypes.string,
  width: PropTypes.string,
  height: PropTypes.string,
};

IconCreditCard.defaultProps = {
  fill: "currentColor",
  width: "1em",
  height: "1em",
};
