// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildIconComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx } from "@emotion/core";
import PropTypes from "prop-types";
import iconStyles from "../Icon.styles";

function IconUpload(props) {
  return (
    <svg
      width={props.width}
      height={props.height}
      xmlns="http://www.w3.org/2000/svg"
      fill={props.fill}
      className="gds-icon"
      css={iconStyles}
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M10.492 13.185a6 6 0 1 0-1.491 11.813H12a1 1 0 0 1 0 2H9a8.004 8.004 0 0 1-7.64-5.649 8 8 0 0 1 9.627-10.102 1 1 0 0 1-.495 1.938z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M22.846 7.46A9 9 0 0 0 11 15.999a1 1 0 1 1-2 0 11 11 0 1 1 19.8 6.6 1 1 0 0 1-1.6-1.2 9.002 9.002 0 0 0-4.354-13.937z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M19 14.998a1 1 0 0 1 .707.293l4.243 4.243a1 1 0 0 1-1.415 1.414L19 17.412l-3.536 3.536a1 1 0 1 1-1.414-1.414l4.243-4.243a1 1 0 0 1 .707-.293z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M19 14.998a1 1 0 0 1 1 1v10a1 1 0 1 1-2 0v-10a1 1 0 0 1 1-1z"
      />
    </svg>
  );
}
export default IconUpload;

IconUpload.propTypes = {
  fill: PropTypes.string,
  width: PropTypes.string,
  height: PropTypes.string,
};

IconUpload.defaultProps = {
  fill: "currentColor",
  width: "1em",
  height: "1em",
};
