// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildIconComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx } from "@emotion/core";
import PropTypes from "prop-types";
import iconStyles from "../Icon.styles";

function IconTrash(props) {
  return (
    <svg
      width={props.width}
      height={props.height}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 32 32"
      fill={props.fill}
      className="gds-icon"
      css={iconStyles}
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M5 6h22a1 1 0 1 1 0 2H5a1 1 0 0 1 0-2zM13 12a1 1 0 0 1 1 1v8a1 1 0 1 1-2 0v-8a1 1 0 0 1 1-1zM19 12a1 1 0 0 1 1 1v8a1 1 0 1 1-2 0v-8a1 1 0 0 1 1-1z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M7 6a1 1 0 0 1 1 1v19h16V7a1 1 0 1 1 2 0v19a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2V7a1 1 0 0 1 1-1z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M10.879 2.879A3 3 0 0 1 13 2h6a3 3 0 0 1 3 3v2a1 1 0 1 1-2 0V5a1 1 0 0 0-1-1h-6a1 1 0 0 0-1 1v2a1 1 0 1 1-2 0V5a3 3 0 0 1 .879-2.121z"
      />
    </svg>
  );
}
export default IconTrash;

IconTrash.propTypes = {
  fill: PropTypes.string,
  width: PropTypes.string,
  height: PropTypes.string,
};

IconTrash.defaultProps = {
  fill: "currentColor",
  width: "1em",
  height: "1em",
};
