// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildIconComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx } from "@emotion/core";
import PropTypes from "prop-types";
import iconStyles from "../Icon.styles";

function IconZoomOut(props) {
  return (
    <svg
      width={props.width}
      height={props.height}
      viewBox="0 0 32 32"
      xmlns="http://www.w3.org/2000/svg"
      fill={props.fill}
      className="gds-icon"
      css={iconStyles}
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M9.5 14.5C9.5 13.9477 9.94772 13.5 10.5 13.5H18.5C19.0523 13.5 19.5 13.9477 19.5 14.5C19.5 15.0523 19.0523 15.5 18.5 15.5H10.5C9.94772 15.5 9.5 15.0523 9.5 14.5Z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M14.5 4.99963C9.25329 4.99963 5 9.25293 5 14.4996C5 19.7463 9.25329 23.9996 14.5 23.9996C19.7467 23.9996 24 19.7463 24 14.4996C24 9.25293 19.7467 4.99963 14.5 4.99963ZM3 14.4996C3 8.14836 8.14873 2.99963 14.5 2.99963C20.8513 2.99963 26 8.14836 26 14.4996C26 20.8509 20.8513 25.9996 14.5 25.9996C8.14873 25.9996 3 20.8509 3 14.4996Z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M21.217 21.2176C21.6075 20.8271 22.2407 20.8271 22.6312 21.2176L28.7063 27.2926C29.0968 27.6832 29.0968 28.3163 28.7063 28.7069C28.3157 29.0974 27.6826 29.0974 27.292 28.7069L21.217 22.6318C20.8264 22.2413 20.8264 21.6081 21.217 21.2176Z"
      />
    </svg>
  );
}
export default IconZoomOut;

IconZoomOut.propTypes = {
  fill: PropTypes.string,
  width: PropTypes.string,
  height: PropTypes.string,
};

IconZoomOut.defaultProps = {
  fill: "currentColor",
  width: "1em",
  height: "1em",
};
