// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildIconComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx } from "@emotion/core";
import PropTypes from "prop-types";
import iconStyles from "../Icon.styles";

function IconGlobe(props) {
  return (
    <svg
      width={props.width}
      height={props.height}
      xmlns="http://www.w3.org/2000/svg"
      fill={props.fill}
      className="gds-icon"
      css={iconStyles}
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M9.23 3.63c.381.38.381.997 0 1.377a11.21 11.21 0 0 0 15.855 15.855.974.974 0 1 1 1.377 1.377A13.158 13.158 0 0 1 7.854 3.63a.974.974 0 0 1 1.377 0zM12.435 28.868c0-.538.436-.974.974-.974h7.498a.974.974 0 0 1 0 1.948H13.41a.974.974 0 0 1-.974-.974z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M17.158 24.145c.538 0 .974.436.974.974v3.749a.974.974 0 1 1-1.947 0v-3.75c0-.537.436-.973.973-.973zM17.158 5.542a7.393 7.393 0 1 0 0 14.787 7.393 7.393 0 0 0 0-14.787zm-9.372 7.393a9.373 9.373 0 1 1 18.745 0 9.373 9.373 0 0 1-18.745 0z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M10.294 19.326a.99.99 0 0 1 0-1.4L22.149 6.071a.99.99 0 0 1 1.4 1.4L11.693 19.325a.99.99 0 0 1-1.4 0z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M12.045 10.23c.54 1.389 1.641 3.05 3.205 4.614 1.563 1.563 3.225 2.665 4.614 3.205.696.27 1.278.383 1.721.374.436-.009.67-.13.8-.26s.252-.365.26-.8c.01-.443-.103-1.026-.374-1.722-.54-1.389-1.641-3.05-3.205-4.614-1.563-1.563-3.225-2.665-4.614-3.205-.696-.27-1.278-.383-1.721-.374-.436.008-.67.13-.8.26s-.252.365-.26.8c-.01.443.103 1.025.374 1.722zM9.692 8.47c.015-.789.248-1.572.839-2.162.59-.59 1.373-.824 2.16-.84.782-.015 1.63.18 2.478.51 1.7.66 3.586 1.939 5.297 3.65 1.71 1.71 2.989 3.596 3.65 5.296.33.849.524 1.696.509 2.477-.016.789-.25 1.572-.84 2.162-.59.59-1.373.823-2.16.839-.782.015-1.63-.178-2.479-.509-1.7-.66-3.585-1.94-5.296-3.65-1.71-1.71-2.989-3.596-3.65-5.296-.33-.849-.524-1.696-.508-2.478z"
      />
    </svg>
  );
}
export default IconGlobe;

IconGlobe.propTypes = {
  fill: PropTypes.string,
  width: PropTypes.string,
  height: PropTypes.string,
};

IconGlobe.defaultProps = {
  fill: "currentColor",
  width: "1em",
  height: "1em",
};
