// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildIconComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx } from "@emotion/core";
import PropTypes from "prop-types";
import iconStyles from "../Icon.styles";

function IconPin(props) {
  return (
    <svg
      width={props.width}
      height={props.height}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 32 32"
      fill={props.fill}
      className="gds-icon"
      css={iconStyles}
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M16 10a3 3 0 1 0 0 6 3 3 0 0 0 0-6zm-5 3a5 5 0 1 1 10 0 5 5 0 0 1-10 0z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M16 4a9 9 0 0 0-9 9c0 4.14 2.312 7.91 4.755 10.719A31.529 31.529 0 0 0 16 27.75a31.529 31.529 0 0 0 4.245-4.031C22.688 20.909 25 17.139 25 13a9 9 0 0 0-9-9zm0 25c-.573.82-.574.819-.574.819l-.003-.002-.008-.006-.025-.018a19.38 19.38 0 0 1-.427-.317c-.286-.218-.69-.538-1.173-.948a33.528 33.528 0 0 1-3.545-3.497C7.688 22.091 5 17.861 5 13a11 11 0 1 1 22 0c0 4.86-2.688 9.09-5.245 12.031a33.528 33.528 0 0 1-3.545 3.497 29.334 29.334 0 0 1-1.508 1.199l-.092.066-.025.018-.008.006-.002.001c-.001.001-.002.001-.575-.818zm0 0 .573.82a1 1 0 0 1-1.146 0L16 29z"
      />
    </svg>
  );
}
export default IconPin;

IconPin.propTypes = {
  fill: PropTypes.string,
  width: PropTypes.string,
  height: PropTypes.string,
};

IconPin.defaultProps = {
  fill: "currentColor",
  width: "1em",
  height: "1em",
};
