// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildIconComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx } from "@emotion/core";
import PropTypes from "prop-types";
import iconStyles from "../Icon.styles";

function IconCamera(props) {
  return (
    <svg
      width={props.width}
      height={props.height}
      viewBox="0 0 32 32"
      xmlns="http://www.w3.org/2000/svg"
      fill={props.fill}
      className="gds-icon"
      css={iconStyles}
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M11.1672 4.4453C11.3527 4.1671 11.6649 4 11.9993 4H19.9993C20.3336 4 20.6459 4.1671 20.8313 4.4453L22.5345 7H26C26.7957 7 27.5587 7.31607 28.1213 7.87868C28.6839 8.44129 29 9.20435 29 10V24C29 24.7957 28.6839 25.5587 28.1213 26.1213C27.5587 26.6839 26.7957 27 26 27H6C5.20435 27 4.44129 26.6839 3.87868 26.1213C3.31607 25.5587 3 24.7957 3 24V10C3 9.20435 3.31607 8.44129 3.87868 7.87868C4.44129 7.31607 5.20435 7 6 7H9.46408L11.1672 4.4453ZM12.5345 6L10.8313 8.5547C10.6459 8.8329 10.3336 9 9.99927 9H6C5.73478 9 5.48043 9.10536 5.29289 9.29289C5.10536 9.48043 5 9.73478 5 10V24C5 24.2652 5.10536 24.5196 5.29289 24.7071C5.48043 24.8946 5.73478 25 6 25H26C26.2652 25 26.5196 24.8946 26.7071 24.7071C26.8946 24.5196 27 24.2652 27 24V10C27 9.73478 26.8946 9.48043 26.7071 9.29289C26.5196 9.10536 26.2652 9 26 9H21.9993C21.6649 9 21.3527 8.8329 21.1672 8.5547L19.4641 6H12.5345Z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M16 13C14.067 13 12.5 14.567 12.5 16.5C12.5 18.433 14.067 20 16 20C17.933 20 19.5 18.433 19.5 16.5C19.5 14.567 17.933 13 16 13ZM10.5 16.5C10.5 13.4624 12.9624 11 16 11C19.0376 11 21.5 13.4624 21.5 16.5C21.5 19.5376 19.0376 22 16 22C12.9624 22 10.5 19.5376 10.5 16.5Z"
      />
    </svg>
  );
}
export default IconCamera;

IconCamera.propTypes = {
  fill: PropTypes.string,
  width: PropTypes.string,
  height: PropTypes.string,
};

IconCamera.defaultProps = {
  fill: "currentColor",
  width: "1em",
  height: "1em",
};
