// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildIconComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

import React from "react";

/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx } from "@emotion/core";
import PropTypes from "prop-types";
import iconStyles from "../Icon.styles";

function IconVisible(props) {
  return (
    <svg
      width={props.width}
      height={props.height}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 32 32"
      fill={props.fill}
      className="gds-icon"
      css={iconStyles}
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M4.543 10.792C6.927 8.408 10.667 6 16 6c5.333 0 9.073 2.41 11.457 4.793a18.917 18.917 0 0 1 2.608 3.269 15.947 15.947 0 0 1 .789 1.404l.042.09.012.026.004.008.001.004L30 16c.914.406.914.407.913.407v.001l-.001.003-.004.008-.012.026a10.255 10.255 0 0 1-.201.405c-.14.268-.349.642-.63 1.089a18.922 18.922 0 0 1-2.608 3.268C25.073 23.59 21.332 25.999 16 25.999c-5.332 0-9.073-2.409-11.457-4.792a18.918 18.918 0 0 1-2.608-3.268 15.955 15.955 0 0 1-.789-1.404 6.213 6.213 0 0 1-.042-.09l-.012-.026-.004-.008v-.003h-.001c0-.001 0-.002.913-.408-.914-.406-.914-.407-.913-.407v-.001l.001-.003.004-.008.012-.026a10.568 10.568 0 0 1 .201-.405c.14-.268.349-.643.63-1.09a18.923 18.923 0 0 1 2.608-3.268zM2 16l-.914-.406a1 1 0 0 0 0 .812L2 16zm1.118 0c.118-.22.287-.52.51-.874a16.92 16.92 0 0 1 2.33-2.92C8.072 10.09 11.332 8 16 8s7.927 2.091 10.043 4.208a16.926 16.926 0 0 1 2.33 2.92c.222.353.391.653.509.873-.118.22-.287.52-.51.873a16.915 16.915 0 0 1-2.33 2.92c-2.115 2.115-5.375 4.206-10.042 4.206-4.668 0-7.927-2.09-10.043-4.207a16.919 16.919 0 0 1-2.33-2.919A14.19 14.19 0 0 1 3.118 16zM30 16l.914.406a1 1 0 0 0 0-.812L30 16z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M16 12a4 4 0 1 0 0 8 4 4 0 0 0 0-8zm-6 4a6 6 0 1 1 12 0 6 6 0 0 1-12 0z"
      />
    </svg>
  );
}
export default IconVisible;

IconVisible.propTypes = {
  /**
   * A CSS fill color.
   */
  fill: PropTypes.string,
  /**
   * Any valid CSS width value.
   */
  width: PropTypes.string,
  /**
   * Any valid CSS height value.
   */
  height: PropTypes.string,
};

IconVisible.defaultProps = {
  fill: "currentColor",
  width: "100%",
  height: "100%",
};
