// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildIconComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx } from "@emotion/core";
import PropTypes from "prop-types";
import iconStyles from "../Icon.styles";

function IconLock(props) {
  return (
    <svg
      width={props.width}
      height={props.height}
      xmlns="http://www.w3.org/2000/svg"
      fill={props.fill}
      className="gds-icon"
      css={iconStyles}
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M16 16a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm-3.5 1.5a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M16 19a1 1 0 0 1 1 1v3a1 1 0 1 1-2 0v-3a1 1 0 0 1 1-1z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M4 12a2 2 0 0 1 2-2h20a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V12zm22 0H6v14h20V12z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M16 3a3.5 3.5 0 0 0-3.5 3.5V11a1 1 0 1 1-2 0V6.5a5.5 5.5 0 1 1 11 0V11a1 1 0 1 1-2 0V6.5A3.5 3.5 0 0 0 16 3z"
      />
    </svg>
  );
}
export default IconLock;

IconLock.propTypes = {
  fill: PropTypes.string,
  width: PropTypes.string,
  height: PropTypes.string,
};

IconLock.defaultProps = {
  fill: "currentColor",
  width: "1em",
  height: "1em",
};
