// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildIconComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx } from "@emotion/core";
import PropTypes from "prop-types";
import iconStyles from "../Icon.styles";

function IconArrowClockwise(props) {
  return (
    <svg
      width={props.width}
      height={props.height}
      viewBox="0 0 32 32"
      xmlns="http://www.w3.org/2000/svg"
      fill={props.fill}
      className="gds-icon"
      css={iconStyles}
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M28.021 5.46448C28.5733 5.46448 29.021 5.91219 29.021 6.46448V12.4645C29.021 13.0168 28.5733 13.4645 28.021 13.4645H22.021C21.4687 13.4645 21.021 13.0168 21.021 12.4645C21.021 11.9122 21.4687 11.4645 22.021 11.4645H27.021V6.46448C27.021 5.91219 27.4687 5.46448 28.021 5.46448Z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M17.9509 6.19215C16.0111 5.8063 14.0004 6.00433 12.1732 6.76121C10.3459 7.51809 8.78412 8.79981 7.6853 10.4443C6.58649 12.0888 6 14.0222 6 16C6 17.9778 6.58649 19.9112 7.6853 21.5557C8.78412 23.2002 10.3459 24.4819 12.1732 25.2388C14.0004 25.9957 16.0111 26.1937 17.9509 25.8079C19.8907 25.422 21.6725 24.4696 23.0711 23.0711C23.4616 22.6805 24.0948 22.6805 24.4853 23.0711C24.8758 23.4616 24.8758 24.0948 24.4853 24.4853C22.8071 26.1635 20.6689 27.3064 18.3411 27.7694C16.0133 28.2325 13.6005 27.9948 11.4078 27.0866C9.21509 26.1783 7.34094 24.6402 6.02236 22.6668C4.70379 20.6935 4 18.3734 4 16C4 13.6266 4.70379 11.3066 6.02236 9.33316C7.34094 7.35977 9.21509 5.8217 11.4078 4.91345C13.6005 4.0052 16.0133 3.76756 18.3411 4.23058C20.6689 4.6936 22.8071 5.83649 24.4853 7.51472L28.7279 11.7574C29.1184 12.1479 29.1184 12.7811 28.7279 13.1716C28.3374 13.5621 27.7042 13.5621 27.3137 13.1716L23.0711 8.92894C21.6725 7.53041 19.8907 6.578 17.9509 6.19215Z"
      />
    </svg>
  );
}
export default IconArrowClockwise;

IconArrowClockwise.propTypes = {
  fill: PropTypes.string,
  width: PropTypes.string,
  height: PropTypes.string,
};

IconArrowClockwise.defaultProps = {
  fill: "currentColor",
  width: "1em",
  height: "1em",
};
