// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildIconComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx } from "@emotion/core";
import PropTypes from "prop-types";
import iconStyles from "../Icon.styles";

function IconZoomIn(props) {
  return (
    <svg
      width={props.width}
      height={props.height}
      viewBox="0 0 32 32"
      xmlns="http://www.w3.org/2000/svg"
      fill={props.fill}
      className="gds-icon"
      css={iconStyles}
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M9.5 14.5C9.5 13.9477 9.94772 13.5 10.5 13.5H18.5C19.0523 13.5 19.5 13.9477 19.5 14.5C19.5 15.0523 19.0523 15.5 18.5 15.5H10.5C9.94772 15.5 9.5 15.0523 9.5 14.5Z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M14.5 9.5C15.0523 9.5 15.5 9.94772 15.5 10.5V18.5C15.5 19.0523 15.0523 19.5 14.5 19.5C13.9477 19.5 13.5 19.0523 13.5 18.5V10.5C13.5 9.94772 13.9477 9.5 14.5 9.5Z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M14.5 4.99951C9.25329 4.99951 5 9.25281 5 14.4995C5 19.7462 9.25329 23.9995 14.5 23.9995C19.7467 23.9995 24 19.7462 24 14.4995C24 9.25281 19.7467 4.99951 14.5 4.99951ZM3 14.4995C3 8.14824 8.14873 2.99951 14.5 2.99951C20.8513 2.99951 26 8.14824 26 14.4995C26 20.8508 20.8513 25.9995 14.5 25.9995C8.14873 25.9995 3 20.8508 3 14.4995Z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M21.217 21.2175C21.6075 20.8269 22.2407 20.8269 22.6312 21.2175L28.7063 27.2925C29.0968 27.6831 29.0968 28.3162 28.7063 28.7067C28.3157 29.0973 27.6826 29.0973 27.292 28.7067L21.217 22.6317C20.8264 22.2411 20.8264 21.608 21.217 21.2175Z"
      />
    </svg>
  );
}
export default IconZoomIn;

IconZoomIn.propTypes = {
  fill: PropTypes.string,
  width: PropTypes.string,
  height: PropTypes.string,
};

IconZoomIn.defaultProps = {
  fill: "currentColor",
  width: "1em",
  height: "1em",
};
