// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildIconComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx } from "@emotion/core";
import PropTypes from "prop-types";
import iconStyles from "../Icon.styles";

function IconSmile(props) {
  return (
    <svg
      width={props.width}
      height={props.height}
      viewBox="0 0 32 32"
      xmlns="http://www.w3.org/2000/svg"
      fill={props.fill}
      className="gds-icon"
      css={iconStyles}
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M16 5C9.92487 5 5 9.92487 5 16C5 22.0751 9.92487 27 16 27C22.0751 27 27 22.0751 27 16C27 9.92487 22.0751 5 16 5ZM3 16C3 8.8203 8.8203 3 16 3C23.1797 3 29 8.8203 29 16C29 23.1797 23.1797 29 16 29C8.8203 29 3 23.1797 3 16Z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M21.6977 18.1338C22.1758 18.4102 22.3393 19.0219 22.0629 19.5C21.448 20.5637 20.564 21.4468 19.4998 22.0608C18.4356 22.6748 17.2286 22.9981 16 22.9981C14.7713 22.9981 13.5643 22.6749 12.5001 22.0609C11.4359 21.4469 10.5519 20.5638 9.93694 19.5001C9.6605 19.022 9.824 18.4103 10.3021 18.1339C10.7802 17.8574 11.3919 18.0209 11.6684 18.4991C12.1077 19.259 12.7393 19.8899 13.4996 20.3285C14.2599 20.7672 15.1222 20.9981 15.9999 20.9981C16.8777 20.9981 17.74 20.7671 18.5003 20.3285C19.2606 19.8898 19.8921 19.2589 20.3315 18.499C20.6079 18.0209 21.2196 17.8574 21.6977 18.1338Z"
      />
      <path d="M11.5 15C12.3284 15 13 14.3284 13 13.5C13 12.6716 12.3284 12 11.5 12C10.6716 12 10 12.6716 10 13.5C10 14.3284 10.6716 15 11.5 15Z" />
      <path d="M20.5 15C21.3284 15 22 14.3284 22 13.5C22 12.6716 21.3284 12 20.5 12C19.6716 12 19 12.6716 19 13.5C19 14.3284 19.6716 15 20.5 15Z" />
    </svg>
  );
}
export default IconSmile;

IconSmile.propTypes = {
  fill: PropTypes.string,
  width: PropTypes.string,
  height: PropTypes.string,
};

IconSmile.defaultProps = {
  fill: "currentColor",
  width: "1em",
  height: "1em",
};
