// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildIconComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx } from "@emotion/core";
import PropTypes from "prop-types";
import iconStyles from "../Icon.styles";

function IconGear(props) {
  return (
    <svg
      width={props.width}
      height={props.height}
      xmlns="http://www.w3.org/2000/svg"
      fill={props.fill}
      className="gds-icon"
      css={iconStyles}
      {...props}
    >
      <path
        d="M16 22a6 6 0 1 0 0-12 6 6 0 0 0 0 12z"
        stroke="#000"
        strokeWidth={2}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M15.359 5.52 13 3.75a1 1 0 0 0-.897-.155c-.73.229-1.44.522-2.118.876a1 1 0 0 0-.526.746l-.417 2.919a10.716 10.716 0 0 0-.906.906h0l-2.919.418a1 1 0 0 0-.744.524 12.92 12.92 0 0 0-.878 2.117 1 1 0 0 0 .155.9l1.77 2.358a10.706 10.706 0 0 0 0 1.282h0L3.75 19a1 1 0 0 0-.155.897c.229.73.522 1.44.876 2.118a1 1 0 0 0 .746.526l2.919.417a10.7 10.7 0 0 0 .906.906h0l.418 2.919a.999.999 0 0 0 .524.744c.678.355 1.387.649 2.117.878a1 1 0 0 0 .9-.155l2.358-1.77a10.717 10.717 0 0 0 1.282 0h0L19 28.25a1 1 0 0 0 .897.155c.73-.229 1.44-.522 2.118-.876a1 1 0 0 0 .526-.746l.417-2.919a10.75 10.75 0 0 0 .906-.906h0l2.919-.418a1 1 0 0 0 .744-.524c.355-.678.649-1.387.878-2.117a1 1 0 0 0-.155-.9l-1.77-2.358a10.717 10.717 0 0 0 0-1.282h0L28.25 13a.999.999 0 0 0 .155-.897c-.229-.73-.522-1.44-.876-2.118a1 1 0 0 0-.746-.526l-2.919-.417a10.771 10.771 0 0 0-.906-.906h0l-.418-2.919a1 1 0 0 0-.524-.744 12.92 12.92 0 0 0-2.117-.878 1 1 0 0 0-.9.155l-2.358 1.77a10.706 10.706 0 0 0-1.282 0h0z"
        stroke="#000"
        strokeWidth={2}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}
export default IconGear;

IconGear.propTypes = {
  fill: PropTypes.string,
  width: PropTypes.string,
  height: PropTypes.string,
};

IconGear.defaultProps = {
  fill: "currentColor",
  width: "1em",
  height: "1em",
};
