// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildIconComponents.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
import React from 'react';
import PropTypes from 'prop-types';
import iconStyles from '../Icon.styles';

const SvgLink = (props) => (
  <svg
    width="1em"
    height="1em"
    fill={props.fill}
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 32 32"
    className="gds-icon"
    css={iconStyles}
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M23.38 6.184a4.5 4.5 0 0 0-4.905.977L16 9.636a1 1 0 0 1-1.414-1.414l2.474-2.475a6.502 6.502 0 0 1 9.195-.002 6.499 6.499 0 0 1-.002 9.194l-3.535 3.536a6.5 6.5 0 0 1-9.193 0 1 1 0 0 1 1.414-1.414 4.5 4.5 0 0 0 6.364 0l3.536-3.536a4.502 4.502 0 0 0-1.459-7.341Z"
      fill={props.fill}
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M13.879 13.621a4.499 4.499 0 0 0-3.182 1.318L7.16 18.475a4.502 4.502 0 0 0-.002 6.366 4.499 4.499 0 0 0 6.366-.002L16 22.364a1 1 0 0 1 1.414 1.414l-2.474 2.475a6.5 6.5 0 1 1-9.193-9.193l3.535-3.535a6.502 6.502 0 0 1 9.193 0 1 1 0 1 1-1.414 1.414 4.498 4.498 0 0 0-3.182-1.318Z"
      fill={props.fill}
    />
  </svg>
);

SvgLink.propTypes = {
  /**
   * A CSS fill color.
   */
  fill: PropTypes.string,

  /**
   * Any valid CSS width value.
   */
  width: PropTypes.string,

  /**
   * Any valid CSS height value.
   */
  height: PropTypes.string,
};
SvgLink.defaultProps = {
  fill: 'currentColor',
  width: '100%',
  height: '100%',
};
export default SvgLink;
