#!/usr/bin/env node

import fs from 'fs';
import path from 'path';

const header = `// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildIndexJs.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

import raw from 'raw.macro';

`;

const partnerCountriesFolder = `${path.resolve()}/svg/partner-countries`;
const programCountriesFolder = `${path.resolve()}/svg/program-countries`;

fs.readdir(partnerCountriesFolder, (err, svgs) => {
  let svgExports = header;

  if (err) {
    console.error(err);
  }

  svgs.forEach((svg) => {
    const name = svg.replace(/\.svg/, '');

    svgExports += `export const ${name.replace(
      ' ',
      ''
    )} = raw('./svg/partner-countries/${svg}');\n`;
  });

  fs.writeFile(`${path.resolve()}/partner-countries.js`, svgExports, (er) => {
    if (er) {
      console.error(er);
    }
  });
});

fs.readdir(programCountriesFolder, (err, svgs) => {
  let svgExports = header;

  if (err) {
    console.error(err);
  }

  svgs.forEach((svg) => {
    const name = svg.replace(/\.svg/, '');

    svgExports += `export const ${name.replace(
      ' ',
      ''
    )} = raw('./svg/program-countries/${svg}');\n`;
  });

  fs.writeFile(`${path.resolve()}/program-countries.js`, svgExports, (er) => {
    if (er) {
      console.error(er);
    }
  });
});
