#!/usr/bin/env node

import fs from 'fs';
import path from 'path';

const header = `// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// DO NOT MODIFY THIS FILE; IT WAS GENERATED BY buildIndexJs.mjs.
// =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

import raw from 'raw.macro';

`;

const buildExports = (svgDirectory, baseName) => {
  fs.readdir(svgDirectory, (err, svgs) => {
    let svgExports = header;

    if (err) {
      console.error(err);
    }

    svgs.forEach((svg) => {
      const name = svg.replace(/\.svg/, '');

      svgExports += `export const ${name.replace(
        ' ',
        ''
      )} = raw('./svg/${baseName}/${svg}');\n`;
    });

    fs.writeFile(`${path.resolve()}/${baseName}.js`, svgExports, (er) => {
      if (er) {
        console.error(er);
      }
    });
  });
};

['partner-countries', 'program-countries'].forEach((baseName) => {
  buildExports(`${path.resolve()}/svg/${baseName}`, baseName);
});
