# Name of the action visible in the action overview
name: Storybook

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for the following branches
  push:
    branches: [development, main]
  pull_request:
    branches: [development, main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Snapshot capturing related work
jobs:
  percy-snapshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Capture storybook snapshots each package
        run: npm run percy-snapshots:packages
        env:
          PERCY_TOKEN_REACT: ${{ secrets.PERCY_TOKEN_REACT_WEB }}
          PERCY_TOKEN_CORE: ${{ secrets.PERCY_TOKEN_WEB_COMPONENTS }}
