# Name of the action visible in the action overview
name: Storybook

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for the following branches
  push:
    branches: [ development, main ]
  pull_request:
    branches: [ development, main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Snapshot capturing related work
jobs:
  build_storybooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build storybook for each package
        run: npm run build:storybooks
      - name: Upload Storybook Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: storybook bundles
          path: packages/*/storybook-static/**
  capture_snapshots:
    runs-on: ubuntu-latest
    needs: build_storybooks
    strategy:
      matrix:
        include:
#          - package: react
#            token: PERCY_TOKEN_REACT_WEB
          - package: css
            token: PERCY_TOKEN_WEB_COMPONENTS
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Download Storybook Artifacts
        uses: actions/download-artifact@v2
        with:
          name: storybook bundles
      # We don't need to install all of our dependencies but percy
      - name: Install dependencies
        run: npm i --silent @percy/cli @percy/storybook
      - name: Capture snapshots
        env:
          PERCY_TOKEN: ${{ secrets[matrix.token] }}
          BUNDLE_PATH: ${{ format('{0}/storybook-static', matrix.package) }}
        run: npx percy storybook $BUNDLE_PATH

  # todo: a job for GH pages: https://github.com/compassion-gds/compassion-gds/issues/89
